$axure.loadCurrentPage({
  "url":"добавление_из_альбома.html",
  "generationDate":new Date(1429122558531.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"52593c77c10e4263987d89f7c7c3a4c9",
    "type":"Axure:Page",
    "name":"Добавление из альбома",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90f95ec52c384e27949ae0cb2624fd3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":20,
              "y":122},
            "size":{
              "width":228,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0b7532f1844482f87d74781ff72a094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":122},
                "size":{
                  "width":228,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51a1b086ccf544a7968e1a1596cd63f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":630,
              "y":128},
            "size":{
              "width":250,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173a218658054d4b9aa4768365146800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":630,
                  "y":128},
                "size":{
                  "width":250,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Редактирование in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"редактирование.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/добавление_из_альбома/u2.png"}},
{
          "id":"853911899a4a4ef8a5136ef37cdd5490",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9046ec8f2be745efa91c4c72c9820cdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"804131d05f414e0b810bb1bddd33b4fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8147b0900fb46b4a6f6ab97b70c8bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a01ae9e60b24c86925671c543c5f8ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":522,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0e95c9e48a456285ecd8faf7b09211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":522,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45b77a4da679495abd0ddbd55c3969f0",
          "label":"фото1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":350,
              "y":182},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee3b7f16f30b4175919a4219f7b86951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":350,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"6b41c4c6f4724fd4883a2f1a111f2c0b",
          "label":"фото2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":490,
              "y":182},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f883f254d0394af5825e74c40deb1d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":490,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"a392e73b3a6d4f0eaac619a342b02b6b",
          "label":"фото3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":630,
              "y":182},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c369a8e013346bd9d5f0881fbc1f331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":630,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"e10e9dcf137f492e97f4fd234ceb89cf",
          "label":"назв1",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":350,
              "y":296},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3378e9b6ea384cde8c3af8447f95d095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":350,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"083d3906afc04797804b00f2b95b3198",
          "label":"назв2",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":490,
              "y":296},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9f0e69115e47f58b662de17aab66a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":490,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"05ceb7123e134434b04f3eb35c9644e9",
          "label":"назв3",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":630,
              "y":296},
            "size":{
              "width":110,
              "height":32},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df290810a2bf49b2a11ab3a3730a08e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":630,
                  "y":296},
                "size":{
                  "width":110,
                  "height":32},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"7f1db42a1d434f16a94f97ec690ced1f",
          "label":"фото5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":350,
              "y":372},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88649b60cce45cda62f3aeccf22e48d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":350,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"e06ab23626914d609095774552da3738",
          "label":"фото6",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":490,
              "y":372},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05b5060f2a7848e5ba650221b6f3ee57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":490,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"cec3ba01d7a743f1a1fa8c98419013fa",
          "label":"фото7",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":630,
              "y":372},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b436729b384d43bd9b3fedb95345ffd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":630,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"5cc74a8c0d154b9aadd862b4e72e5710",
          "label":"назв5",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":350,
              "y":486},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3153f28bb38f4a3095b1f6996e621a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":350,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"4bafa9b3e93b437ab041af4974ff812c",
          "label":"назв6",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":490,
              "y":486},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc7a5ca811049c5a1772c8e911e0331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":490,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"dae06c32e4374c0e97d370076f10557c",
          "label":"назв7",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":630,
              "y":486},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64b4a09212a44899110d22c43fe6a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":630,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"536d27338ff5437fb549c12e2ee34548",
          "label":"фото4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":770,
              "y":182},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed0d931e35b4754bac2898445d2e192",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":770,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"74a22cd25c1c428780590ae0de72e7a2",
          "label":"назв4",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":770,
              "y":296},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8296efadaa504e77ab77be4f7075d087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":770,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"584918e59ff3414da8d76bf658de491e",
          "label":"фото8",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":770,
              "y":372},
            "size":{
              "width":110,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3dff0246c6d463ba4c2cc2dc2c85171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":770,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"38be6c320553490f980c33393a692785",
          "label":"назв8",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":false,
          "style":{
            "location":{
              "x":770,
              "y":486},
            "size":{
              "width":110,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525330d83c504c6e8315c261e41a12b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":770,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}]},
{
          "id":"9e871c2a90994b88be26f5d0baa1135e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":350,
              "y":128},
            "size":{
              "width":93,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab819dfeac7b41a0b344e241d4b8da74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":128},
                "size":{
                  "width":93,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u40.png"}},
{
          "id":"68a222b43ee14ae4b87d7ed854b21ac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":453,
              "y":128},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"463641c9629747b4a8390315a1958e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":128},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u42.png"}},
{
          "id":"c3de39255a1d41acadc412de1284a01d",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":182},
            "size":{
              "width":219,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265a9ea03bc74c6e961234bb3546ca74",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "size":{
                  "width":137,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"368d1c231bf0448ba1e3e776b9752c2a",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "size":{
                      "width":137,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"259d6de95e414aa9afc229cf1b6aa14b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "size":{
                          "width":137,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}}],
              "buttonShapeId":"368d1c231bf0448ba1e3e776b9752c2a"},
{
              "id":"6c4dff14bd824214b7c255c39928bc8e",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0c5d4569b874489a236fc5d3a8762f1",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a04a07b32ce40b4973b4c0db0abbdb6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":78,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}},
{
                  "id":"986e3106604047a581f7309185ba4d06",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":114,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd7aeb67a69d4ca998b5ef038cd5f8a1",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":114,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6a0e65d1d9c24d66a075fba298683083",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":114,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}},
{
                      "id":"c61670a3a06f498bace142466c02af76",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":119,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a59f972eafca4bb8b05cd9d672da6f92",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":119,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9a9cd8a2df7f4bcda46ef8d469b9f320",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":119,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"fadeWidget",
                                  "description":"Toggle фото1,<br>фото2,<br>фото3,<br>назв1,<br>назв2,<br>назв3,<br>фото5,<br>фото6,<br>фото7,<br>назв5,<br>назв6,<br>назв7,<br>фото4,<br>назв4,<br>фото8,<br>назв8",
                                  "objectsToFades":[{
                                      "objectPath":["45b77a4da679495abd0ddbd55c3969f0"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["6b41c4c6f4724fd4883a2f1a111f2c0b"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["a392e73b3a6d4f0eaac619a342b02b6b"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["e10e9dcf137f492e97f4fd234ceb89cf"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["083d3906afc04797804b00f2b95b3198"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["05ceb7123e134434b04f3eb35c9644e9"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["7f1db42a1d434f16a94f97ec690ced1f"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["e06ab23626914d609095774552da3738"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["cec3ba01d7a743f1a1fa8c98419013fa"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["5cc74a8c0d154b9aadd862b4e72e5710"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["4bafa9b3e93b437ab041af4974ff812c"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["dae06c32e4374c0e97d370076f10557c"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["536d27338ff5437fb549c12e2ee34548"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["74a22cd25c1c428780590ae0de72e7a2"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["584918e59ff3414da8d76bf658de491e"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["38be6c320553490f980c33393a692785"],
                                      "fadeInfo":{
                                        "fadeType":"toggle",
                                        "options":{
                                          "showType":"none"}}}]}]}]}},
                      "tabbable":true,
                      "buttonShapeId":"a59f972eafca4bb8b05cd9d672da6f92"},
{
                      "id":"3693bcf4c0f7436bbb0524821cff6855",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4252814b37ec45269915d6f62ed64d54",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/добавление_из_альбома/u51.png",
                        "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                      "id":"18e0f2888ee74a0099f480818a524bc3",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":121,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b0d4e3df545d42d3ae3e2c5aaadaec7b",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":121,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"899e1261ddf44698bdfdf4b9eb874b32",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":80},
                                "size":{
                                  "width":121,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"b0d4e3df545d42d3ae3e2c5aaadaec7b"},
{
                      "id":"859c9c64ca9a41dd87cfcd27adba3708",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":126,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"00ac04be5344468890fd29f44481584f",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":126,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"80b9b2cf96e74073a3c1ff40367acd3e",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":60},
                                "size":{
                                  "width":126,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"00ac04be5344468890fd29f44481584f"},
{
                      "id":"8751c86a1e8043acbab86edf7078b812",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":172,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bc78ad0388a64fe8869081318c7776d3",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":172,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"69999a562c10451d85a74291b25564cb",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":172,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"bc78ad0388a64fe8869081318c7776d3"}],
                  "buttonShapeId":"cd7aeb67a69d4ca998b5ef038cd5f8a1"},
{
                  "id":"d27aafca46624e0cac65f0001dccfd2c",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16a961fff9844a9a99dc1ed3691f2ec1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/добавление_из_альбома/u51.png",
                    "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                  "id":"32e27c5b674a44e69f71c43e20b4a00d",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":120},
                    "size":{
                      "width":129,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db8ea9f875104e4397eb991c3152411d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":120},
                        "size":{
                          "width":129,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"10ba9a0bbd974c7990102030e7688c86",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":120},
                            "size":{
                              "width":129,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"db8ea9f875104e4397eb991c3152411d"},
{
                  "id":"f3654b373f034ecaba94f7137079ba6c",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":140},
                    "size":{
                      "width":199,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e6de7b416644615b8e1f5d80f18303d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":140},
                        "size":{
                          "width":199,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"da017b01f4f44dc4a427cb96508aa2f6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":140},
                            "size":{
                              "width":199,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"3e6de7b416644615b8e1f5d80f18303d"}],
              "buttonShapeId":"f0c5d4569b874489a236fc5d3a8762f1"},
{
              "id":"2810630bce1e4b8b9b9a2cedeec62c22",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":0,
                  "y":280},
                "size":{
                  "width":128,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc50ff0032e941048d61097b67c1f62f",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":128,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b90e5d9367dc495fb2067cac5d5ae66b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":0,
                          "y":280},
                        "size":{
                          "width":128,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}}],
              "buttonShapeId":"cc50ff0032e941048d61097b67c1f62f"},
{
              "id":"4d697cb94975404eb9bcc481bd7643de",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a70458ebc26b4dc2ab2fe43acf3fbd0c",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"643ba04d5498468284439710e764888d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":0,
                          "y":180},
                        "size":{
                          "width":132,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}},
{
                  "id":"9200c88829604110855e4a8af9f3e35e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":142,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9edd97cefacb4444bbb8ae497e9895f2",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":142,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"55c6132288074361a47c311630129451",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":142,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"9edd97cefacb4444bbb8ae497e9895f2"},
{
                  "id":"18118beeaa7a4c2a919205aec34978db",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1635d64125f481da01ae2d8be98aeff",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/добавление_из_альбома/u51.png",
                    "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                  "id":"00c657fde0ab402f898e7786dda71edb",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":129,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18476a39e3984c6694a6327ea5927bb0",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":129,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"15b4a2ea22474393915f148d6f3fd4e7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":129,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"18476a39e3984c6694a6327ea5927bb0"},
{
                  "id":"0876c256c8094598b871a1ea11d82307",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"854f2fe3bd4543748162e09435f92e07",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":66,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"410e011ae34e401688d2eda55fc3c2ba",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":66,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"854f2fe3bd4543748162e09435f92e07"},
{
                  "id":"6a2020effa00442d93ffbf091ab1bd9a",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":105,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fdc7b36794643038217c30681fafadd",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":105,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ab4cb3e6899c4e0f93885be60be6398a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":105,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"1fdc7b36794643038217c30681fafadd"}],
              "buttonShapeId":"a70458ebc26b4dc2ab2fe43acf3fbd0c"}]}]}},
  "masters":{
},
  "objectPaths":{
    "90f95ec52c384e27949ae0cb2624fd3e":{
      "scriptId":"u0"},
    "e0b7532f1844482f87d74781ff72a094":{
      "scriptId":"u1"},
    "51a1b086ccf544a7968e1a1596cd63f8":{
      "scriptId":"u2"},
    "173a218658054d4b9aa4768365146800":{
      "scriptId":"u3"},
    "853911899a4a4ef8a5136ef37cdd5490":{
      "scriptId":"u4"},
    "9046ec8f2be745efa91c4c72c9820cdc":{
      "scriptId":"u5"},
    "804131d05f414e0b810bb1bddd33b4fc":{
      "scriptId":"u6"},
    "c8147b0900fb46b4a6f6ab97b70c8bb0":{
      "scriptId":"u7"},
    "0a01ae9e60b24c86925671c543c5f8ec":{
      "scriptId":"u8"},
    "ec0e95c9e48a456285ecd8faf7b09211":{
      "scriptId":"u9"},
    "45b77a4da679495abd0ddbd55c3969f0":{
      "scriptId":"u10"},
    "ee3b7f16f30b4175919a4219f7b86951":{
      "scriptId":"u11"},
    "6b41c4c6f4724fd4883a2f1a111f2c0b":{
      "scriptId":"u12"},
    "f883f254d0394af5825e74c40deb1d55":{
      "scriptId":"u13"},
    "a392e73b3a6d4f0eaac619a342b02b6b":{
      "scriptId":"u14"},
    "7c369a8e013346bd9d5f0881fbc1f331":{
      "scriptId":"u15"},
    "e10e9dcf137f492e97f4fd234ceb89cf":{
      "scriptId":"u16"},
    "3378e9b6ea384cde8c3af8447f95d095":{
      "scriptId":"u17"},
    "083d3906afc04797804b00f2b95b3198":{
      "scriptId":"u18"},
    "4c9f0e69115e47f58b662de17aab66a7":{
      "scriptId":"u19"},
    "05ceb7123e134434b04f3eb35c9644e9":{
      "scriptId":"u20"},
    "df290810a2bf49b2a11ab3a3730a08e2":{
      "scriptId":"u21"},
    "7f1db42a1d434f16a94f97ec690ced1f":{
      "scriptId":"u22"},
    "f88649b60cce45cda62f3aeccf22e48d":{
      "scriptId":"u23"},
    "e06ab23626914d609095774552da3738":{
      "scriptId":"u24"},
    "05b5060f2a7848e5ba650221b6f3ee57":{
      "scriptId":"u25"},
    "cec3ba01d7a743f1a1fa8c98419013fa":{
      "scriptId":"u26"},
    "b436729b384d43bd9b3fedb95345ffd8":{
      "scriptId":"u27"},
    "5cc74a8c0d154b9aadd862b4e72e5710":{
      "scriptId":"u28"},
    "3153f28bb38f4a3095b1f6996e621a97":{
      "scriptId":"u29"},
    "4bafa9b3e93b437ab041af4974ff812c":{
      "scriptId":"u30"},
    "efc7a5ca811049c5a1772c8e911e0331":{
      "scriptId":"u31"},
    "dae06c32e4374c0e97d370076f10557c":{
      "scriptId":"u32"},
    "e64b4a09212a44899110d22c43fe6a4f":{
      "scriptId":"u33"},
    "536d27338ff5437fb549c12e2ee34548":{
      "scriptId":"u34"},
    "7ed0d931e35b4754bac2898445d2e192":{
      "scriptId":"u35"},
    "74a22cd25c1c428780590ae0de72e7a2":{
      "scriptId":"u36"},
    "8296efadaa504e77ab77be4f7075d087":{
      "scriptId":"u37"},
    "584918e59ff3414da8d76bf658de491e":{
      "scriptId":"u38"},
    "a3dff0246c6d463ba4c2cc2dc2c85171":{
      "scriptId":"u39"},
    "38be6c320553490f980c33393a692785":{
      "scriptId":"u40"},
    "525330d83c504c6e8315c261e41a12b4":{
      "scriptId":"u41"},
    "9e871c2a90994b88be26f5d0baa1135e":{
      "scriptId":"u42"},
    "ab819dfeac7b41a0b344e241d4b8da74":{
      "scriptId":"u43"},
    "68a222b43ee14ae4b87d7ed854b21ac9":{
      "scriptId":"u44"},
    "463641c9629747b4a8390315a1958e06":{
      "scriptId":"u45"},
    "c3de39255a1d41acadc412de1284a01d":{
      "scriptId":"u46"},
    "265a9ea03bc74c6e961234bb3546ca74":{
      "scriptId":"u47"},
    "368d1c231bf0448ba1e3e776b9752c2a":{
      "scriptId":"u48"},
    "259d6de95e414aa9afc229cf1b6aa14b":{
      "scriptId":"u49"},
    "6c4dff14bd824214b7c255c39928bc8e":{
      "scriptId":"u50"},
    "d27aafca46624e0cac65f0001dccfd2c":{
      "scriptId":"u51"},
    "16a961fff9844a9a99dc1ed3691f2ec1":{
      "scriptId":"u52"},
    "f0c5d4569b874489a236fc5d3a8762f1":{
      "scriptId":"u53"},
    "9a04a07b32ce40b4973b4c0db0abbdb6":{
      "scriptId":"u54"},
    "986e3106604047a581f7309185ba4d06":{
      "scriptId":"u55"},
    "3693bcf4c0f7436bbb0524821cff6855":{
      "scriptId":"u56"},
    "4252814b37ec45269915d6f62ed64d54":{
      "scriptId":"u57"},
    "cd7aeb67a69d4ca998b5ef038cd5f8a1":{
      "scriptId":"u58"},
    "6a0e65d1d9c24d66a075fba298683083":{
      "scriptId":"u59"},
    "c61670a3a06f498bace142466c02af76":{
      "scriptId":"u60"},
    "a59f972eafca4bb8b05cd9d672da6f92":{
      "scriptId":"u61"},
    "9a9cd8a2df7f4bcda46ef8d469b9f320":{
      "scriptId":"u62"},
    "8751c86a1e8043acbab86edf7078b812":{
      "scriptId":"u63"},
    "bc78ad0388a64fe8869081318c7776d3":{
      "scriptId":"u64"},
    "69999a562c10451d85a74291b25564cb":{
      "scriptId":"u65"},
    "859c9c64ca9a41dd87cfcd27adba3708":{
      "scriptId":"u66"},
    "00ac04be5344468890fd29f44481584f":{
      "scriptId":"u67"},
    "80b9b2cf96e74073a3c1ff40367acd3e":{
      "scriptId":"u68"},
    "18e0f2888ee74a0099f480818a524bc3":{
      "scriptId":"u69"},
    "b0d4e3df545d42d3ae3e2c5aaadaec7b":{
      "scriptId":"u70"},
    "899e1261ddf44698bdfdf4b9eb874b32":{
      "scriptId":"u71"},
    "32e27c5b674a44e69f71c43e20b4a00d":{
      "scriptId":"u72"},
    "db8ea9f875104e4397eb991c3152411d":{
      "scriptId":"u73"},
    "10ba9a0bbd974c7990102030e7688c86":{
      "scriptId":"u74"},
    "f3654b373f034ecaba94f7137079ba6c":{
      "scriptId":"u75"},
    "3e6de7b416644615b8e1f5d80f18303d":{
      "scriptId":"u76"},
    "da017b01f4f44dc4a427cb96508aa2f6":{
      "scriptId":"u77"},
    "4d697cb94975404eb9bcc481bd7643de":{
      "scriptId":"u78"},
    "18118beeaa7a4c2a919205aec34978db":{
      "scriptId":"u79"},
    "b1635d64125f481da01ae2d8be98aeff":{
      "scriptId":"u80"},
    "a70458ebc26b4dc2ab2fe43acf3fbd0c":{
      "scriptId":"u81"},
    "643ba04d5498468284439710e764888d":{
      "scriptId":"u82"},
    "9200c88829604110855e4a8af9f3e35e":{
      "scriptId":"u83"},
    "9edd97cefacb4444bbb8ae497e9895f2":{
      "scriptId":"u84"},
    "55c6132288074361a47c311630129451":{
      "scriptId":"u85"},
    "00c657fde0ab402f898e7786dda71edb":{
      "scriptId":"u86"},
    "18476a39e3984c6694a6327ea5927bb0":{
      "scriptId":"u87"},
    "15b4a2ea22474393915f148d6f3fd4e7":{
      "scriptId":"u88"},
    "0876c256c8094598b871a1ea11d82307":{
      "scriptId":"u89"},
    "854f2fe3bd4543748162e09435f92e07":{
      "scriptId":"u90"},
    "410e011ae34e401688d2eda55fc3c2ba":{
      "scriptId":"u91"},
    "6a2020effa00442d93ffbf091ab1bd9a":{
      "scriptId":"u92"},
    "1fdc7b36794643038217c30681fafadd":{
      "scriptId":"u93"},
    "ab4cb3e6899c4e0f93885be60be6398a":{
      "scriptId":"u94"},
    "2810630bce1e4b8b9b9a2cedeec62c22":{
      "scriptId":"u95"},
    "cc50ff0032e941048d61097b67c1f62f":{
      "scriptId":"u96"},
    "b90e5d9367dc495fb2067cac5d5ae66b":{
      "scriptId":"u97"}}});