$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1429122551797.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6ae1bddb4248413281420c539376d11c",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a5b272fbc6be42798ae0a33f8889185a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":13},
            "size":{
              "width":286,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b272f2f89844fb80a495619c0b4a40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":13},
                "size":{
                  "width":286,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00a0ed0fe64f467cac186a3068be9923",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":72},
            "size":{
              "width":220,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b87474560249edbfe85cf08ac189b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":72},
                "size":{
                  "width":220,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фото по поездкам in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фото_по_поездкам.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3406b2bd73154fb6ad00d0689acaa9a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":110},
            "size":{
              "width":285,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271508d9074a4ea6817239ca5925798c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":110},
                "size":{
                  "width":285,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Избранные фото кого-то in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"избранные_фото_кого-то.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c293b0f7f2e46ac85e0e2c17b311738",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":148},
            "size":{
              "width":279,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a14a2619744e4d84897f4cc653b272a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":148},
                "size":{
                  "width":279,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Избранные фото кого-то in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"избранные_фото_кого-то.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40472496a40542db9bf34597f8c4a602",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":230},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e2a0c99b0043af86fc15cb8b933daa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":20,
                  "y":230},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a5b272fbc6be42798ae0a33f8889185a":{
      "scriptId":"u0"},
    "52b272f2f89844fb80a495619c0b4a40":{
      "scriptId":"u1"},
    "00a0ed0fe64f467cac186a3068be9923":{
      "scriptId":"u2"},
    "85b87474560249edbfe85cf08ac189b0":{
      "scriptId":"u3"},
    "3406b2bd73154fb6ad00d0689acaa9a7":{
      "scriptId":"u4"},
    "271508d9074a4ea6817239ca5925798c":{
      "scriptId":"u5"},
    "9c293b0f7f2e46ac85e0e2c17b311738":{
      "scriptId":"u6"},
    "a14a2619744e4d84897f4cc653b272a5":{
      "scriptId":"u7"},
    "40472496a40542db9bf34597f8c4a602":{
      "scriptId":"u8"},
    "f7e2a0c99b0043af86fc15cb8b933daa":{
      "scriptId":"u9"}}});