$axure.loadCurrentPage({
  "url":"редактирование.html",
  "generationDate":new Date(1429122557332.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69f504f27da44af8af8a8b06c3af3bb9",
    "type":"Axure:Page",
    "name":"Редактирование",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e0b12e2dca41499fbb7d01523a2ddacb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":182},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3945567531be4357b9510611eb1f7058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"8e80f0078a77434bb99787fb362cb4f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":182},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efee95b2f6e4ebca5bf9d4daffebe0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"342357362ce5440d9af41cdec2074209",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":182},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9c09790cbb4dd0be68247ebe87c3ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"f3eb6abf18bb46609beae006e58a9f8a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":296},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f530d4d6d44fc0a6fa33eb1806865c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"78cc516ba11048cf8a8a5dc07d0b359f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":296},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99587e51c27e446aa710aa5683bdc2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eef2f7e37d114d2587d2a49e10ab6c23",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":296},
            "size":{
              "width":110,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb67b90092644d29b651cc8a53d3b9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":296},
                "size":{
                  "width":110,
                  "height":32}},
              "adaptiveStyles":{
}}]},
{
          "id":"41e8a7443a194fefb526cd028b955945",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":372},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75209f0768c04d40b80785d572d32ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"68ea8a5484c94853a814f770afd9ea56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":372},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b189727c74aa404aa5e137d415bfec67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"bfe96080b230451a80b3fbf4bcac31fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":372},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44258e09825d435a8325889549f585f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"828d88f5be724eeeb3f52fa16e8b32d0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":486},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecac571d8fc842ae87d46360dd9bd104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8fa308fe8be448c7b50e732d340c1bd9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":486},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e125517639a4a3fbcd5de2c6db6f4b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b9fcd2efc5bc444eb37baaf9275cb3ab",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":486},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af901ac13bd247d3843beb698c054af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"99ae70a4568b403a846fca3ceb6d5f0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":41,
              "y":182},
            "size":{
              "width":178,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"756e1a673f2a4d8db543b8b37c83a0af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":41,
                  "y":182},
                "size":{
                  "width":178,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f598cb6016104b09b81f54f90bed7819",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":41,
              "y":269},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c257a5028dd4091ab79f150bb6c758a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":41,
                  "y":269},
                "size":{
                  "width":180,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe7ae873d2942649bde073946090b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":41,
              "y":469},
            "size":{
              "width":183,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e000c4138f4005aa7c67f51a24f317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":41,
                  "y":469},
                "size":{
                  "width":183,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aca10be763dd4233af3915853e18617c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":41,
              "y":383},
            "size":{
              "width":177,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47615c16ac464a52bf58c3f336964527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":41,
                  "y":383},
                "size":{
                  "width":177,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1a6926a56a1473a82578ffbfb76a161",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":182},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c009ae2e4ab1466b98328047438c3da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":182},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"23fb594d5aaf432ba81591f9ce607083",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":296},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c719f4814a4e4e85ba8c46cc07f9125c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":296},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fc198545354a4e3e8fc1378e81787b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":372},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c44cb1f42c848aa8820aceec64c3408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":372},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u0.png"}},
{
          "id":"38a69c15fd3e455e857efb95dc93500a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":486},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8540c121723c4308974cae1bcb132541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":486},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"19b0a739074445c6b35a2f4df559928b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":128},
            "size":{
              "width":93,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633b3386e17b4add9fe4f610c39b6993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":128},
                "size":{
                  "width":93,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u40.png"}},
{
          "id":"fd4bd7d42e6544f98da4c5f71700a1e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":128},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c586856307b9432ca6cdb53f6d925521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":128},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u42.png"}},
{
          "id":"4af693a1de0c4ccd99eda21e4580e57e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":723,
              "y":132},
            "size":{
              "width":107,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c80752124fd444609419ced0f6268932",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":658,
              "y":135},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39b32fd9201c4453a5cf034f72e601e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":658,
                  "y":135},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db1fbf8d449545fa9ec6b35b2db62996",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":214},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8d2f0e79793e43a789dc867841214885",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":415},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"919d52fb277a4193b7b7d4ee075ca9a4",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":301},
            "size":{
              "width":189,
              "height":61}},
          "adaptiveStyles":{
}},
{
          "id":"910b2b33605549fda7fe3f769cf4836d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":129},
            "size":{
              "width":200,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18b1d8d47634f09ac8919953c138641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":129},
                "size":{
                  "width":200,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ed1b6544020481ab00b5158216c3764",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":555},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6b3291398a4ba7b4449807d493d21c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":555},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"31807912e7cb48b6805d504681fbae7d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":581},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2798fff60d441bfa09f060f464a0978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":581},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"722eed63e15c42d9b2975af8898b1685",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":607},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71334cca2eaa418d9655e35cc3253517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":607},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9b6bba53e62042edba5cf1e201ae5c39",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":633},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3795e96fc9e94d5391b94b3ba28fb2f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":633},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b8a93c2f164d42009b08f4b5b930e0eb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":659},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef441f9212d24b8cb8b33737825d6843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":659},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"49176ce24e9742beb54b86cd6f4754df",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":683},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b72dcccdc44cacbb8e97e6f04ab24d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":683},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c2596a8acf7c437f88b4325684b6cc49",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":735},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b22e96ecb54c7692c66af717db8300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":735},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cc0557f165ec481199df933a61a8b682",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":761},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f698777d98904258ac03a35cf6b8915c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":761},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c121015541ff4550b4cc8300bed6a6ca",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":787},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed00833f1ca641c1871f85aca163c9f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":787},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"be3d9015f6e545d6b8ba619a1fe8648a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":813},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1558510596964a2da8816631ee8aa9f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":813},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3a5ea9b241e94a6e84c4eb68f407f61a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":839},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ecd3bd9e105419181da72ca3fb88be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":839},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b0027f7fc6c04c9296546d4cc8784ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":347,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367ff54c038d48e7aa66929abd0e81cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":347,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e29e0e044e6a48ccb2c5fe1ad74348bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":501},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64804e90c5ea471fb2b2a0e1d40e9583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":501},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1ba5572fe09441cbe7f28269b99b8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":527},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24816f88778f4a8dbd059969a09c176a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":527},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bcdfd0834544c95a2f49ea0dfe33de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":709},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"550e3084c678429bad5da3a0f7395a46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":709},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcc1f3770c7d4c57b2444ed6af5e2110",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28471c246f974b1b93cee4b3f99f816f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0793a100fcf45e49cde0daad64dc340",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"077bd4c0da2c48558b42ead46a32d741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87ac143b3e334e13af53fa047db8fc02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":128},
            "size":{
              "width":115,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac779fea2d3641e9a47ade353166f0e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":533,
                  "y":128},
                "size":{
                  "width":115,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u86.png"}},
{
          "id":"09d554f1e64e4c7fa4cb01c49c1591e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":172},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e98ee3b6b044713958e887c7316ee96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":172},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u88.png"}},
{
          "id":"80d48dccfeeb42baada89e91aee5c453",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":589,
              "y":172},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368a74d650f84c65ab54498a0270711e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":589,
                  "y":172},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u88.png"}},
{
          "id":"18b86d58c0e44759a0d78c9a06eba31a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":172},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d47a3cec2076406da53ab6f125338305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":172},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u88.png"}},
{
          "id":"9dc0a51dc2cc4277b9502d7ff68fc246",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":869,
              "y":172},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8674d6772a13483aaffaf6663a6937d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":869,
                  "y":172},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u88.png"}},
{
          "id":"6a1f81f55dc8446ba2eebc5fc0ee9a9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":362},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb7a7569ef04c85b84c764a2dd7fb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":362},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u88.png"}},
{
          "id":"591fb7665a1f42a3830a0722260e580d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":780,
              "y":32},
            "size":{
              "width":130,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb9053a564d462880fa4cc9850b9e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":32},
                "size":{
                  "width":130,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Результат редактирования in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"результат_редактирования.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u98.png"}},
{
          "id":"ff2ab535f01f45a2b3c023df4ad0e9f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":350,
              "y":80},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77f2ddee3137454f80c09e9930e63e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":80},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"74caec4044d049ba991f9d93c8ec9bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":636,
              "y":80},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"720d99c75069460bb495e45f95005e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":80},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Добавление из альбома in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"добавление_из_альбома.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"9423ddc2404042db8cee9a857486c86b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":636,
              "y":32},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3363987d034ec2a104c2b9b9dbc306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":32},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"c82911503d4747e7809da14b2be93de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":80},
            "size":{
              "width":132,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5159cf9cfb74b218064b11df215a462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":80},
                "size":{
                  "width":132,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u106.png"}},
{
          "id":"1b396b1c6a9440358b28916a12e38e17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":780,
              "y":80},
            "size":{
              "width":130,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b2e39e831a48009666349778f5466f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":80},
                "size":{
                  "width":130,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show Загрузка",
                      "objectsToFades":[{
                          "objectPath":["8fc0a149951f42d8ab1b2f832619d3a7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u98.png"}},
{
          "id":"8fc0a149951f42d8ab1b2f832619d3a7",
          "label":"Загрузка",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":97,
              "y":10},
            "size":{
              "width":683,
              "height":560},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ba574829f84634854aea9ced69d766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":97,
                  "y":10},
                "size":{
                  "width":683,
                  "height":560},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide This",
                      "objectsToFades":[{
                          "objectPath":["8fc0a149951f42d8ab1b2f832619d3a7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/админка/загрузка_u12.PNG"}}]}},
  "masters":{
},
  "objectPaths":{
    "e0b12e2dca41499fbb7d01523a2ddacb":{
      "scriptId":"u0"},
    "3945567531be4357b9510611eb1f7058":{
      "scriptId":"u1"},
    "8e80f0078a77434bb99787fb362cb4f4":{
      "scriptId":"u2"},
    "3efee95b2f6e4ebca5bf9d4daffebe0c":{
      "scriptId":"u3"},
    "342357362ce5440d9af41cdec2074209":{
      "scriptId":"u4"},
    "6b9c09790cbb4dd0be68247ebe87c3ae":{
      "scriptId":"u5"},
    "f3eb6abf18bb46609beae006e58a9f8a":{
      "scriptId":"u6"},
    "15f530d4d6d44fc0a6fa33eb1806865c":{
      "scriptId":"u7"},
    "78cc516ba11048cf8a8a5dc07d0b359f":{
      "scriptId":"u8"},
    "99587e51c27e446aa710aa5683bdc2d7":{
      "scriptId":"u9"},
    "eef2f7e37d114d2587d2a49e10ab6c23":{
      "scriptId":"u10"},
    "bb67b90092644d29b651cc8a53d3b9e5":{
      "scriptId":"u11"},
    "41e8a7443a194fefb526cd028b955945":{
      "scriptId":"u12"},
    "75209f0768c04d40b80785d572d32ac5":{
      "scriptId":"u13"},
    "68ea8a5484c94853a814f770afd9ea56":{
      "scriptId":"u14"},
    "b189727c74aa404aa5e137d415bfec67":{
      "scriptId":"u15"},
    "bfe96080b230451a80b3fbf4bcac31fe":{
      "scriptId":"u16"},
    "44258e09825d435a8325889549f585f0":{
      "scriptId":"u17"},
    "828d88f5be724eeeb3f52fa16e8b32d0":{
      "scriptId":"u18"},
    "ecac571d8fc842ae87d46360dd9bd104":{
      "scriptId":"u19"},
    "8fa308fe8be448c7b50e732d340c1bd9":{
      "scriptId":"u20"},
    "7e125517639a4a3fbcd5de2c6db6f4b2":{
      "scriptId":"u21"},
    "b9fcd2efc5bc444eb37baaf9275cb3ab":{
      "scriptId":"u22"},
    "af901ac13bd247d3843beb698c054af0":{
      "scriptId":"u23"},
    "99ae70a4568b403a846fca3ceb6d5f0c":{
      "scriptId":"u24"},
    "756e1a673f2a4d8db543b8b37c83a0af":{
      "scriptId":"u25"},
    "f598cb6016104b09b81f54f90bed7819":{
      "scriptId":"u26"},
    "6c257a5028dd4091ab79f150bb6c758a":{
      "scriptId":"u27"},
    "abe7ae873d2942649bde073946090b2a":{
      "scriptId":"u28"},
    "90e000c4138f4005aa7c67f51a24f317":{
      "scriptId":"u29"},
    "aca10be763dd4233af3915853e18617c":{
      "scriptId":"u30"},
    "47615c16ac464a52bf58c3f336964527":{
      "scriptId":"u31"},
    "f1a6926a56a1473a82578ffbfb76a161":{
      "scriptId":"u32"},
    "c009ae2e4ab1466b98328047438c3da5":{
      "scriptId":"u33"},
    "23fb594d5aaf432ba81591f9ce607083":{
      "scriptId":"u34"},
    "c719f4814a4e4e85ba8c46cc07f9125c":{
      "scriptId":"u35"},
    "fc198545354a4e3e8fc1378e81787b27":{
      "scriptId":"u36"},
    "5c44cb1f42c848aa8820aceec64c3408":{
      "scriptId":"u37"},
    "38a69c15fd3e455e857efb95dc93500a":{
      "scriptId":"u38"},
    "8540c121723c4308974cae1bcb132541":{
      "scriptId":"u39"},
    "19b0a739074445c6b35a2f4df559928b":{
      "scriptId":"u40"},
    "633b3386e17b4add9fe4f610c39b6993":{
      "scriptId":"u41"},
    "fd4bd7d42e6544f98da4c5f71700a1e3":{
      "scriptId":"u42"},
    "c586856307b9432ca6cdb53f6d925521":{
      "scriptId":"u43"},
    "4af693a1de0c4ccd99eda21e4580e57e":{
      "scriptId":"u44"},
    "c80752124fd444609419ced0f6268932":{
      "scriptId":"u45"},
    "39b32fd9201c4453a5cf034f72e601e2":{
      "scriptId":"u46"},
    "db1fbf8d449545fa9ec6b35b2db62996":{
      "scriptId":"u47"},
    "8d2f0e79793e43a789dc867841214885":{
      "scriptId":"u48"},
    "919d52fb277a4193b7b7d4ee075ca9a4":{
      "scriptId":"u49"},
    "910b2b33605549fda7fe3f769cf4836d":{
      "scriptId":"u50"},
    "f18b1d8d47634f09ac8919953c138641":{
      "scriptId":"u51"},
    "5ed1b6544020481ab00b5158216c3764":{
      "scriptId":"u52"},
    "ab6b3291398a4ba7b4449807d493d21c":{
      "scriptId":"u53"},
    "31807912e7cb48b6805d504681fbae7d":{
      "scriptId":"u54"},
    "e2798fff60d441bfa09f060f464a0978":{
      "scriptId":"u55"},
    "722eed63e15c42d9b2975af8898b1685":{
      "scriptId":"u56"},
    "71334cca2eaa418d9655e35cc3253517":{
      "scriptId":"u57"},
    "9b6bba53e62042edba5cf1e201ae5c39":{
      "scriptId":"u58"},
    "3795e96fc9e94d5391b94b3ba28fb2f2":{
      "scriptId":"u59"},
    "b8a93c2f164d42009b08f4b5b930e0eb":{
      "scriptId":"u60"},
    "ef441f9212d24b8cb8b33737825d6843":{
      "scriptId":"u61"},
    "49176ce24e9742beb54b86cd6f4754df":{
      "scriptId":"u62"},
    "e1b72dcccdc44cacbb8e97e6f04ab24d":{
      "scriptId":"u63"},
    "c2596a8acf7c437f88b4325684b6cc49":{
      "scriptId":"u64"},
    "38b22e96ecb54c7692c66af717db8300":{
      "scriptId":"u65"},
    "cc0557f165ec481199df933a61a8b682":{
      "scriptId":"u66"},
    "f698777d98904258ac03a35cf6b8915c":{
      "scriptId":"u67"},
    "c121015541ff4550b4cc8300bed6a6ca":{
      "scriptId":"u68"},
    "ed00833f1ca641c1871f85aca163c9f3":{
      "scriptId":"u69"},
    "be3d9015f6e545d6b8ba619a1fe8648a":{
      "scriptId":"u70"},
    "1558510596964a2da8816631ee8aa9f2":{
      "scriptId":"u71"},
    "3a5ea9b241e94a6e84c4eb68f407f61a":{
      "scriptId":"u72"},
    "0ecd3bd9e105419181da72ca3fb88be4":{
      "scriptId":"u73"},
    "b0027f7fc6c04c9296546d4cc8784ee4":{
      "scriptId":"u74"},
    "367ff54c038d48e7aa66929abd0e81cd":{
      "scriptId":"u75"},
    "e29e0e044e6a48ccb2c5fe1ad74348bd":{
      "scriptId":"u76"},
    "64804e90c5ea471fb2b2a0e1d40e9583":{
      "scriptId":"u77"},
    "d1ba5572fe09441cbe7f28269b99b8ad":{
      "scriptId":"u78"},
    "24816f88778f4a8dbd059969a09c176a":{
      "scriptId":"u79"},
    "5bcdfd0834544c95a2f49ea0dfe33de7":{
      "scriptId":"u80"},
    "550e3084c678429bad5da3a0f7395a46":{
      "scriptId":"u81"},
    "bcc1f3770c7d4c57b2444ed6af5e2110":{
      "scriptId":"u82"},
    "28471c246f974b1b93cee4b3f99f816f":{
      "scriptId":"u83"},
    "b0793a100fcf45e49cde0daad64dc340":{
      "scriptId":"u84"},
    "077bd4c0da2c48558b42ead46a32d741":{
      "scriptId":"u85"},
    "87ac143b3e334e13af53fa047db8fc02":{
      "scriptId":"u86"},
    "ac779fea2d3641e9a47ade353166f0e8":{
      "scriptId":"u87"},
    "09d554f1e64e4c7fa4cb01c49c1591e5":{
      "scriptId":"u88"},
    "8e98ee3b6b044713958e887c7316ee96":{
      "scriptId":"u89"},
    "80d48dccfeeb42baada89e91aee5c453":{
      "scriptId":"u90"},
    "368a74d650f84c65ab54498a0270711e":{
      "scriptId":"u91"},
    "18b86d58c0e44759a0d78c9a06eba31a":{
      "scriptId":"u92"},
    "d47a3cec2076406da53ab6f125338305":{
      "scriptId":"u93"},
    "9dc0a51dc2cc4277b9502d7ff68fc246":{
      "scriptId":"u94"},
    "8674d6772a13483aaffaf6663a6937d7":{
      "scriptId":"u95"},
    "6a1f81f55dc8446ba2eebc5fc0ee9a9d":{
      "scriptId":"u96"},
    "feb7a7569ef04c85b84c764a2dd7fb6a":{
      "scriptId":"u97"},
    "591fb7665a1f42a3830a0722260e580d":{
      "scriptId":"u98"},
    "4fb9053a564d462880fa4cc9850b9e95":{
      "scriptId":"u99"},
    "ff2ab535f01f45a2b3c023df4ad0e9f9":{
      "scriptId":"u100"},
    "77f2ddee3137454f80c09e9930e63e4c":{
      "scriptId":"u101"},
    "74caec4044d049ba991f9d93c8ec9bfe":{
      "scriptId":"u102"},
    "720d99c75069460bb495e45f95005e02":{
      "scriptId":"u103"},
    "9423ddc2404042db8cee9a857486c86b":{
      "scriptId":"u104"},
    "7c3363987d034ec2a104c2b9b9dbc306":{
      "scriptId":"u105"},
    "c82911503d4747e7809da14b2be93de5":{
      "scriptId":"u106"},
    "e5159cf9cfb74b218064b11df215a462":{
      "scriptId":"u107"},
    "1b396b1c6a9440358b28916a12e38e17":{
      "scriptId":"u108"},
    "09b2e39e831a48009666349778f5466f":{
      "scriptId":"u109"},
    "8fc0a149951f42d8ab1b2f832619d3a7":{
      "scriptId":"u110"},
    "a8ba574829f84634854aea9ced69d766":{
      "scriptId":"u111"}}});