$axure.loadCurrentPage({
  "url":"отмена_невозможна.html",
  "generationDate":new Date(1429122556266.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b3d339bf5914904ba2639bbe4eff333",
    "type":"Axure:Page",
    "name":"Отмена невозможна",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bfb962411c5f49b79b0bc2161eab58f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":20,
              "y":140},
            "size":{
              "width":360,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e55d1c1794f4ef8a9ea9bb4bfa160bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":20,
                  "y":140},
                "size":{
                  "width":360,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c5ac64c0569428f87682ce325146376",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":369,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6cbd4b16b6b4ea88f491f7b2a888cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":369,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5051aedc2bb1492585cfa7221b4779ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c303c6da766948af97f448a039c8fc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59b059bd2e9d4ccfbad0b48be03292f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52ffc9a959154bb89d9b90cad28d0fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f89f4d34624041bc80c8d21315b6d764",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":290,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff2e7538d6046958dcbccd5ec9306a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":290,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/результат_быстрой_загрузки/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bfb962411c5f49b79b0bc2161eab58f1":{
      "scriptId":"u0"},
    "5e55d1c1794f4ef8a9ea9bb4bfa160bf":{
      "scriptId":"u1"},
    "4c5ac64c0569428f87682ce325146376":{
      "scriptId":"u2"},
    "b6cbd4b16b6b4ea88f491f7b2a888cce":{
      "scriptId":"u3"},
    "5051aedc2bb1492585cfa7221b4779ed":{
      "scriptId":"u4"},
    "c303c6da766948af97f448a039c8fc87":{
      "scriptId":"u5"},
    "59b059bd2e9d4ccfbad0b48be03292f5":{
      "scriptId":"u6"},
    "52ffc9a959154bb89d9b90cad28d0fbf":{
      "scriptId":"u7"},
    "f89f4d34624041bc80c8d21315b6d764":{
      "scriptId":"u8"},
    "5ff2e7538d6046958dcbccd5ec9306a5":{
      "scriptId":"u9"}}});