$axure.loadCurrentPage({
  "url":"день_1.html",
  "generationDate":new Date(1429122553231.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"caa1ac4d92bd4096b6850d7ba645def1",
    "type":"Axure:Page",
    "name":"День 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1bad80bdb69244bcb7bf904c7acb6b0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":400,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d229c645864cc0856d6b2df5f04541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":400,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5a0ff460ae849b2ab86951ec9df2c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"280351bfddcb4ec59f6ec74bb5fae216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"d53b73357d354b12896e66eb842b155b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0847bf77b1004d43b83d5feb5cb1be36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"59fcda89086144dea22f31bbbf62dc3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":274},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"707cd5c7b160463eb42ce882a2a48580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":274},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d52efa5e7904f719a74d2a541a89360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":274},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7aa8e7fdf04092a1106a0251011939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":274},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf89d3f1c74640ac9bef2185282bae19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75219d20d1c34cfdaf2663ebf2fb37e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"cbfeddee18344b5e8f9ec86147adba33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055ea24d4e2943d8b7047ad08c793535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"b1eae9d3f3cb4d009ae256fd8ff05d52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":274},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b807b1d15d420f9eba1cc04cfed2e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":274},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d9cd85068314050ae9bb28cdc51fe03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":274},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24bb536c89ed4796b9588f13ed76b5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":274},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1433353604fd417e82bad7b0f5c1503c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d754849d65b4436a1bb95005f348b34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"fad28a45b5c94de7a2ba17ca8b942299",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2629657eb942ae973905513176e7d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"98357d79929c4ba2bf1f7aaa480619d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":274},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a11c55194d4c57aa32d86a8e50fb33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":274},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0b880ce2987441488ebe621468c2b24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":274},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"391009f2709b48218b864c2b2c061b56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":274},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"558e9733ffdf4e9bb6a13543529cf1e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fd0f3b68f4941eea0abd5f0e1e7be03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"921f0d00cefc400b907a3cff7474f337",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acba23c87b27404fb003ed58b8f587a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"06046bbd6e824eca9d871c3f0999e16e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46bbf5f6bb74c5d954495baa1e453f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12639f71d8bd45fa9de7c9d99e2ed984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1059307c5ab43e38b0ee5bf9ab6a55c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ec2ae3a2548417fb66c9ba2f5ec48e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a806fdfc81d4f568f69f7a05e6771ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"14f1d2dcdba04881901eb35f3c5cbc36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cb6fd91967f4644aa1bfe274d8d35eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"f26790b81a534348af4aabe93c87baef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cc13635675e48d8a457e8c555e3311e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53310c054de44b82a33f6e702e074bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":454},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c302806451f41b8934ea34d0232c0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":454},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5a5ea4140c461b8bbf4f34cce9344b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26ad8faffd1485a9fb99c9a2f0970b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"94c730c7c12840378f4dfe9cdc10a034",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766ac8269e0f4b61885ba2bfcfd5abcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"07a91f9307494df2b783730d91e825d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":454},
            "size":{
              "width":94,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9b8272a6e84100934ac03b8971fcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":454},
                "size":{
                  "width":94,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3c4316cb84245ef93a956bbc53a7a6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":454},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d8e4a7cd9f45aba4c6153c5ebbfd54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":454},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7b7d551348446e2a0a2bd0a401b825d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc3f8c1658f4e929675e88a7aac15b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"a92b955b80fb40d39ce506bc0416d965",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2678f6282d4a45c28ff10e28457573d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"c9c5d1a971e24b9f9f397d16be95153f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172be61907214b01a6fa212227eeaf57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"334e2e5c323840fe8b3ae73d0b1292a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d217cf0a9a24911b5adb5c8141678c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe45696e2a8a4a9b9dfe34f97a2a1894",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5299f4c25a14afb85f533160872af9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"844993ba697c4160b9fee3979ce6f3eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a7443f6d107417f8b7fdc603b7f1580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"0a04d0feab7b42ddb0d3f42abcefc4a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1821c46704947c194b60d9cdb5a9499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eeddf89a3c74a608347fb37cd28d957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":634},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b31869f2eef47e7b3064f6234cc6126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":634},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c662f6aea2044088878b14a2eccc303",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bba711f40c4a4b469d8c06702feafb10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"3624d77eb48e4adc9b71121be1adc2c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e55810aadb46fdaa941ab021bac636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"66c827c4563e44488a7240d979c0e4ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f565b5648f4406a09a5ac424364dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d64755a638542eab16432d34e313a6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c19cf98481a4b00a6a7a81b23a093f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78836b29bf4f41afaa19c567b5981576",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":67},
            "size":{
              "width":135,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab9f6514f814bbcbe8a1dc5b6634719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":67},
                "size":{
                  "width":135,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фото по поездкам in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фото_по_поездкам.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecc20e702f034ac18f8ddb0a1147015c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":67},
            "size":{
              "width":201,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab830d0e637c4b20afff8013ee0df211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":67},
                "size":{
                  "width":201,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Псков 2014 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"псков_2014.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f934505bd5264f18b7b891f007efa413",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":110},
            "size":{
              "width":170,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23377b1f52fc4cce86acdf3e6acbff99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":110},
                "size":{
                  "width":170,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/день_1/u78.png"}},
{
          "id":"d172db1bf3e74326ba356757c708a170",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f3e91e448d464eadc7bb5207b96c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1bad80bdb69244bcb7bf904c7acb6b0c":{
      "scriptId":"u0"},
    "59d229c645864cc0856d6b2df5f04541":{
      "scriptId":"u1"},
    "a5a0ff460ae849b2ab86951ec9df2c89":{
      "scriptId":"u2"},
    "280351bfddcb4ec59f6ec74bb5fae216":{
      "scriptId":"u3"},
    "d53b73357d354b12896e66eb842b155b":{
      "scriptId":"u4"},
    "0847bf77b1004d43b83d5feb5cb1be36":{
      "scriptId":"u5"},
    "59fcda89086144dea22f31bbbf62dc3e":{
      "scriptId":"u6"},
    "707cd5c7b160463eb42ce882a2a48580":{
      "scriptId":"u7"},
    "4d52efa5e7904f719a74d2a541a89360":{
      "scriptId":"u8"},
    "7c7aa8e7fdf04092a1106a0251011939":{
      "scriptId":"u9"},
    "cf89d3f1c74640ac9bef2185282bae19":{
      "scriptId":"u10"},
    "75219d20d1c34cfdaf2663ebf2fb37e9":{
      "scriptId":"u11"},
    "cbfeddee18344b5e8f9ec86147adba33":{
      "scriptId":"u12"},
    "055ea24d4e2943d8b7047ad08c793535":{
      "scriptId":"u13"},
    "b1eae9d3f3cb4d009ae256fd8ff05d52":{
      "scriptId":"u14"},
    "e2b807b1d15d420f9eba1cc04cfed2e1":{
      "scriptId":"u15"},
    "1d9cd85068314050ae9bb28cdc51fe03":{
      "scriptId":"u16"},
    "24bb536c89ed4796b9588f13ed76b5e5":{
      "scriptId":"u17"},
    "1433353604fd417e82bad7b0f5c1503c":{
      "scriptId":"u18"},
    "9d754849d65b4436a1bb95005f348b34":{
      "scriptId":"u19"},
    "fad28a45b5c94de7a2ba17ca8b942299":{
      "scriptId":"u20"},
    "6d2629657eb942ae973905513176e7d0":{
      "scriptId":"u21"},
    "98357d79929c4ba2bf1f7aaa480619d5":{
      "scriptId":"u22"},
    "52a11c55194d4c57aa32d86a8e50fb33":{
      "scriptId":"u23"},
    "a0b880ce2987441488ebe621468c2b24":{
      "scriptId":"u24"},
    "391009f2709b48218b864c2b2c061b56":{
      "scriptId":"u25"},
    "558e9733ffdf4e9bb6a13543529cf1e8":{
      "scriptId":"u26"},
    "2fd0f3b68f4941eea0abd5f0e1e7be03":{
      "scriptId":"u27"},
    "921f0d00cefc400b907a3cff7474f337":{
      "scriptId":"u28"},
    "acba23c87b27404fb003ed58b8f587a8":{
      "scriptId":"u29"},
    "06046bbd6e824eca9d871c3f0999e16e":{
      "scriptId":"u30"},
    "e46bbf5f6bb74c5d954495baa1e453f3":{
      "scriptId":"u31"},
    "12639f71d8bd45fa9de7c9d99e2ed984":{
      "scriptId":"u32"},
    "a1059307c5ab43e38b0ee5bf9ab6a55c":{
      "scriptId":"u33"},
    "3ec2ae3a2548417fb66c9ba2f5ec48e6":{
      "scriptId":"u34"},
    "8a806fdfc81d4f568f69f7a05e6771ca":{
      "scriptId":"u35"},
    "14f1d2dcdba04881901eb35f3c5cbc36":{
      "scriptId":"u36"},
    "7cb6fd91967f4644aa1bfe274d8d35eb":{
      "scriptId":"u37"},
    "f26790b81a534348af4aabe93c87baef":{
      "scriptId":"u38"},
    "6cc13635675e48d8a457e8c555e3311e":{
      "scriptId":"u39"},
    "53310c054de44b82a33f6e702e074bfe":{
      "scriptId":"u40"},
    "5c302806451f41b8934ea34d0232c0bc":{
      "scriptId":"u41"},
    "0c5a5ea4140c461b8bbf4f34cce9344b":{
      "scriptId":"u42"},
    "f26ad8faffd1485a9fb99c9a2f0970b6":{
      "scriptId":"u43"},
    "94c730c7c12840378f4dfe9cdc10a034":{
      "scriptId":"u44"},
    "766ac8269e0f4b61885ba2bfcfd5abcd":{
      "scriptId":"u45"},
    "07a91f9307494df2b783730d91e825d6":{
      "scriptId":"u46"},
    "ff9b8272a6e84100934ac03b8971fcfb":{
      "scriptId":"u47"},
    "c3c4316cb84245ef93a956bbc53a7a6e":{
      "scriptId":"u48"},
    "79d8e4a7cd9f45aba4c6153c5ebbfd54":{
      "scriptId":"u49"},
    "a7b7d551348446e2a0a2bd0a401b825d":{
      "scriptId":"u50"},
    "8bc3f8c1658f4e929675e88a7aac15b6":{
      "scriptId":"u51"},
    "a92b955b80fb40d39ce506bc0416d965":{
      "scriptId":"u52"},
    "2678f6282d4a45c28ff10e28457573d6":{
      "scriptId":"u53"},
    "c9c5d1a971e24b9f9f397d16be95153f":{
      "scriptId":"u54"},
    "172be61907214b01a6fa212227eeaf57":{
      "scriptId":"u55"},
    "334e2e5c323840fe8b3ae73d0b1292a9":{
      "scriptId":"u56"},
    "2d217cf0a9a24911b5adb5c8141678c7":{
      "scriptId":"u57"},
    "fe45696e2a8a4a9b9dfe34f97a2a1894":{
      "scriptId":"u58"},
    "a5299f4c25a14afb85f533160872af9b":{
      "scriptId":"u59"},
    "844993ba697c4160b9fee3979ce6f3eb":{
      "scriptId":"u60"},
    "1a7443f6d107417f8b7fdc603b7f1580":{
      "scriptId":"u61"},
    "0a04d0feab7b42ddb0d3f42abcefc4a1":{
      "scriptId":"u62"},
    "a1821c46704947c194b60d9cdb5a9499":{
      "scriptId":"u63"},
    "4eeddf89a3c74a608347fb37cd28d957":{
      "scriptId":"u64"},
    "9b31869f2eef47e7b3064f6234cc6126":{
      "scriptId":"u65"},
    "2c662f6aea2044088878b14a2eccc303":{
      "scriptId":"u66"},
    "bba711f40c4a4b469d8c06702feafb10":{
      "scriptId":"u67"},
    "3624d77eb48e4adc9b71121be1adc2c5":{
      "scriptId":"u68"},
    "63e55810aadb46fdaa941ab021bac636":{
      "scriptId":"u69"},
    "66c827c4563e44488a7240d979c0e4ff":{
      "scriptId":"u70"},
    "50f565b5648f4406a09a5ac424364dac":{
      "scriptId":"u71"},
    "5d64755a638542eab16432d34e313a6f":{
      "scriptId":"u72"},
    "4c19cf98481a4b00a6a7a81b23a093f8":{
      "scriptId":"u73"},
    "78836b29bf4f41afaa19c567b5981576":{
      "scriptId":"u74"},
    "8ab9f6514f814bbcbe8a1dc5b6634719":{
      "scriptId":"u75"},
    "ecc20e702f034ac18f8ddb0a1147015c":{
      "scriptId":"u76"},
    "ab830d0e637c4b20afff8013ee0df211":{
      "scriptId":"u77"},
    "f934505bd5264f18b7b891f007efa413":{
      "scriptId":"u78"},
    "23377b1f52fc4cce86acdf3e6acbff99":{
      "scriptId":"u79"},
    "d172db1bf3e74326ba356757c708a170":{
      "scriptId":"u80"},
    "89f3e91e448d464eadc7bb5207b96c51":{
      "scriptId":"u81"}}});