$axure.loadCurrentPage({
  "url":"подборка_фото.html",
  "generationDate":new Date(1429122554314.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a69f6a18f691429db62dcf80a20aa068",
    "type":"Axure:Page",
    "name":"Подборка фото",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ef1c36f5983741f5994e2551a4400cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":20},
            "size":{
              "width":139,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e133f8f3ec5498f9e680085bcd14be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":20},
                "size":{
                  "width":139,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d308e30a76c413e94abacd9219c7d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":302,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"860cd288e90f4db0ad87dfd3a9a249ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":302,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"affce34d4a4548e0bc3bf90e060ad6cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":320,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fac5af73455848c38da88812fd663fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":320,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Избранные фото кого-то in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"избранные_фото_кого-то.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3260cd7830a841fa8a8e81168b1b3260",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235e4043651043969cc7bf2df0a46fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7d84c84d081425aa963f57f639e47c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd6d71226864dee82f4ab2edf6138c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"4a1de5552b3e41ffb7b1e3b428d1312c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbafb1997fc54faa827521387c7d003c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"c2018a9a1db64534a7e086539abed825",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":274},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33236464f3804b5d93d7d389e6ae1ff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":274},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b895e204dcf14d48a32517bef676b2fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":274},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9926a5c2b0c947feabf1828e12661b03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":274},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd2b43aa9aa34492a8bb5f4bef3a25ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b02c8caa84de4e3f99a1bf81a9ed8677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"d2fc882f00af4a8fb67f950175803958",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb097785df304494b245a22340101f87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"70bad147d9b04c118129ff27c82ecc83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":274},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9b2831b6b1c48108fd54e074fc25fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":274},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d877e91fba4a4c3493c36c5f275e2c82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":274},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"123c9324fc1b4988834148eeacc190e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":274},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ac26418ec9469a8b3ed31df3bfa111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3520b88c56664179936070064606f639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"8b2bd6e66bf54fe9860993008eca8400",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":160},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c90f6f025a1346b88c009c7dac5a92fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":160},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"2c1afbf57b424348a3efb40bae96ea06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":274},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d66a1f2d7146959fbcfe19c96f681c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":274},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b707e328d74527910fbcc4ac018b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":274},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9727cb40280b41af934461fed4e7d899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":274},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19f2db5c5a444d5992f1a68bae866bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32d1d8a130054754ab0a6ea33279210e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"c42d4af50622441ca44eef5403e59b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86935e9b848b42d4b76d6d9e73e0ad15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"05df6da09f35481cbe2d1577987acd97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914e427f3a0b425db3ff59409d9430ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618b90179bfd4233a665e043d37300dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516f166e6d9b4d25a3d297a9258e3b7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf4159fb615f4f57b9319de50e54b0ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5f1ad3a01141f995c6b513d16c3e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"cc5839a1a49e4062b6b1d0db28a427b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b8055e53eb497bb12be1ce5c3cb655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"97563776ffa3446aaf8edcf1528ad7db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":454},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f9d955f85b43dc82f1ef4aaeeb3746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":454},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35bf4dda5be84f50ab0e345baee4459f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":454},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff2d18df8e248cc86f31f8e377521b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":454},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a7e4e28ec194566a6023e30bd077700",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d95e8ae19783463a985277bc31b7b87a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"0552666dd99e46f591dfb54a7a1faa9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":340},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"584ccf9077234b0ab242cdb025d344f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":340},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"49b75bcf6d65493e85a26ce4c8ab7cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":454},
            "size":{
              "width":94,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd03fd150564de489c6a353b1b88750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":454},
                "size":{
                  "width":94,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"246d1baf85d4469faa40b7fa12acd145",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":454},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39142a335e3249cb9444611d118e1509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":454},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94f161997db04054bbdc22ea706fbf32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"424891998628478a8b08c5617bcc0d0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"248a7424b59448769cb940cc46ae5f3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a723c4e047b44bf5b3a65faaeb683fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"79112eb62ba5482a902314f9b9a87271",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faf559e2414247babd4892c6a3f59e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74a82ab5c10a483aa6e6c0a610e82dfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55d6c7617b98481ba6140d62f7513b03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f59c60110b14500b306bf1ae5310bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d5140ae0cf647479c280d0ee7719303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"3640584e2af045e2b4df099b15117bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c02d59e1dc6f4a308eca5ef56b748fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"22027ad17e144aa593d820302896d55f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d528926ec4e4de6b87831e3e84fbac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7dca8637fcc4963adb8a52f30c9eb93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":634},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75776c3898c94c52a80dfd8acc9ed4ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":634},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f54ff1dc1b4a4ca0878d2ed61f33b9b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d3d6eeab41e4e4ea52165252c58ac7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"b7445c1d314948c9a2f8dd72c525f5a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":520},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac70802a5cca4d5ab2d57536b8beab5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":520},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/день_1/u2.png"}},
{
          "id":"6eb2659afec342538f986e8aeba8d55e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0778933f444dd79f0c7a772116a90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74edebe35d91498b85f922f0ee38d432",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":634},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6cda1145c1648c9900dacc26c807cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":634},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ef1c36f5983741f5994e2551a4400cc3":{
      "scriptId":"u0"},
    "3e133f8f3ec5498f9e680085bcd14be0":{
      "scriptId":"u1"},
    "4d308e30a76c413e94abacd9219c7d14":{
      "scriptId":"u2"},
    "860cd288e90f4db0ad87dfd3a9a249ca":{
      "scriptId":"u3"},
    "affce34d4a4548e0bc3bf90e060ad6cf":{
      "scriptId":"u4"},
    "fac5af73455848c38da88812fd663fbc":{
      "scriptId":"u5"},
    "3260cd7830a841fa8a8e81168b1b3260":{
      "scriptId":"u6"},
    "235e4043651043969cc7bf2df0a46fc4":{
      "scriptId":"u7"},
    "f7d84c84d081425aa963f57f639e47c6":{
      "scriptId":"u8"},
    "2dd6d71226864dee82f4ab2edf6138c3":{
      "scriptId":"u9"},
    "4a1de5552b3e41ffb7b1e3b428d1312c":{
      "scriptId":"u10"},
    "fbafb1997fc54faa827521387c7d003c":{
      "scriptId":"u11"},
    "c2018a9a1db64534a7e086539abed825":{
      "scriptId":"u12"},
    "33236464f3804b5d93d7d389e6ae1ff5":{
      "scriptId":"u13"},
    "b895e204dcf14d48a32517bef676b2fe":{
      "scriptId":"u14"},
    "9926a5c2b0c947feabf1828e12661b03":{
      "scriptId":"u15"},
    "bd2b43aa9aa34492a8bb5f4bef3a25ef":{
      "scriptId":"u16"},
    "b02c8caa84de4e3f99a1bf81a9ed8677":{
      "scriptId":"u17"},
    "d2fc882f00af4a8fb67f950175803958":{
      "scriptId":"u18"},
    "fb097785df304494b245a22340101f87":{
      "scriptId":"u19"},
    "70bad147d9b04c118129ff27c82ecc83":{
      "scriptId":"u20"},
    "f9b2831b6b1c48108fd54e074fc25fe3":{
      "scriptId":"u21"},
    "d877e91fba4a4c3493c36c5f275e2c82":{
      "scriptId":"u22"},
    "123c9324fc1b4988834148eeacc190e4":{
      "scriptId":"u23"},
    "95ac26418ec9469a8b3ed31df3bfa111":{
      "scriptId":"u24"},
    "3520b88c56664179936070064606f639":{
      "scriptId":"u25"},
    "8b2bd6e66bf54fe9860993008eca8400":{
      "scriptId":"u26"},
    "c90f6f025a1346b88c009c7dac5a92fc":{
      "scriptId":"u27"},
    "2c1afbf57b424348a3efb40bae96ea06":{
      "scriptId":"u28"},
    "b2d66a1f2d7146959fbcfe19c96f681c":{
      "scriptId":"u29"},
    "08b707e328d74527910fbcc4ac018b33":{
      "scriptId":"u30"},
    "9727cb40280b41af934461fed4e7d899":{
      "scriptId":"u31"},
    "19f2db5c5a444d5992f1a68bae866bb7":{
      "scriptId":"u32"},
    "32d1d8a130054754ab0a6ea33279210e":{
      "scriptId":"u33"},
    "c42d4af50622441ca44eef5403e59b00":{
      "scriptId":"u34"},
    "86935e9b848b42d4b76d6d9e73e0ad15":{
      "scriptId":"u35"},
    "05df6da09f35481cbe2d1577987acd97":{
      "scriptId":"u36"},
    "914e427f3a0b425db3ff59409d9430ef":{
      "scriptId":"u37"},
    "618b90179bfd4233a665e043d37300dc":{
      "scriptId":"u38"},
    "516f166e6d9b4d25a3d297a9258e3b7b":{
      "scriptId":"u39"},
    "cf4159fb615f4f57b9319de50e54b0ab":{
      "scriptId":"u40"},
    "bf5f1ad3a01141f995c6b513d16c3e9c":{
      "scriptId":"u41"},
    "cc5839a1a49e4062b6b1d0db28a427b7":{
      "scriptId":"u42"},
    "20b8055e53eb497bb12be1ce5c3cb655":{
      "scriptId":"u43"},
    "97563776ffa3446aaf8edcf1528ad7db":{
      "scriptId":"u44"},
    "55f9d955f85b43dc82f1ef4aaeeb3746":{
      "scriptId":"u45"},
    "35bf4dda5be84f50ab0e345baee4459f":{
      "scriptId":"u46"},
    "2ff2d18df8e248cc86f31f8e377521b2":{
      "scriptId":"u47"},
    "0a7e4e28ec194566a6023e30bd077700":{
      "scriptId":"u48"},
    "d95e8ae19783463a985277bc31b7b87a":{
      "scriptId":"u49"},
    "0552666dd99e46f591dfb54a7a1faa9a":{
      "scriptId":"u50"},
    "584ccf9077234b0ab242cdb025d344f4":{
      "scriptId":"u51"},
    "49b75bcf6d65493e85a26ce4c8ab7cba":{
      "scriptId":"u52"},
    "3cd03fd150564de489c6a353b1b88750":{
      "scriptId":"u53"},
    "246d1baf85d4469faa40b7fa12acd145":{
      "scriptId":"u54"},
    "39142a335e3249cb9444611d118e1509":{
      "scriptId":"u55"},
    "94f161997db04054bbdc22ea706fbf32":{
      "scriptId":"u56"},
    "424891998628478a8b08c5617bcc0d0f":{
      "scriptId":"u57"},
    "248a7424b59448769cb940cc46ae5f3d":{
      "scriptId":"u58"},
    "a723c4e047b44bf5b3a65faaeb683fbc":{
      "scriptId":"u59"},
    "79112eb62ba5482a902314f9b9a87271":{
      "scriptId":"u60"},
    "faf559e2414247babd4892c6a3f59e26":{
      "scriptId":"u61"},
    "74a82ab5c10a483aa6e6c0a610e82dfc":{
      "scriptId":"u62"},
    "55d6c7617b98481ba6140d62f7513b03":{
      "scriptId":"u63"},
    "8f59c60110b14500b306bf1ae5310bc1":{
      "scriptId":"u64"},
    "0d5140ae0cf647479c280d0ee7719303":{
      "scriptId":"u65"},
    "3640584e2af045e2b4df099b15117bd6":{
      "scriptId":"u66"},
    "c02d59e1dc6f4a308eca5ef56b748fb3":{
      "scriptId":"u67"},
    "22027ad17e144aa593d820302896d55f":{
      "scriptId":"u68"},
    "7d528926ec4e4de6b87831e3e84fbac2":{
      "scriptId":"u69"},
    "d7dca8637fcc4963adb8a52f30c9eb93":{
      "scriptId":"u70"},
    "75776c3898c94c52a80dfd8acc9ed4ec":{
      "scriptId":"u71"},
    "f54ff1dc1b4a4ca0878d2ed61f33b9b8":{
      "scriptId":"u72"},
    "9d3d6eeab41e4e4ea52165252c58ac7c":{
      "scriptId":"u73"},
    "b7445c1d314948c9a2f8dd72c525f5a7":{
      "scriptId":"u74"},
    "ac70802a5cca4d5ab2d57536b8beab5e":{
      "scriptId":"u75"},
    "6eb2659afec342538f986e8aeba8d55e":{
      "scriptId":"u76"},
    "5f0778933f444dd79f0c7a772116a90e":{
      "scriptId":"u77"},
    "74edebe35d91498b85f922f0ee38d432":{
      "scriptId":"u78"},
    "c6cda1145c1648c9900dacc26c807cf0":{
      "scriptId":"u79"}}});