$axure.loadCurrentPage({
  "url":"редактирование_пустое.html",
  "generationDate":new Date(1429122557784.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb9daa6d52e641df915bf189d9b59705",
    "type":"Axure:Page",
    "name":"Редактирование пустое",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"99ae70a4568b403a846fca3ceb6d5f0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":182},
            "size":{
              "width":178,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"756e1a673f2a4d8db543b8b37c83a0af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":182},
                "size":{
                  "width":178,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f598cb6016104b09b81f54f90bed7819",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":269},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c257a5028dd4091ab79f150bb6c758a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":269},
                "size":{
                  "width":180,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe7ae873d2942649bde073946090b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":469},
            "size":{
              "width":183,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e000c4138f4005aa7c67f51a24f317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":469},
                "size":{
                  "width":183,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aca10be763dd4233af3915853e18617c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":383},
            "size":{
              "width":177,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47615c16ac464a52bf58c3f336964527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":383},
                "size":{
                  "width":177,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4af693a1de0c4ccd99eda21e4580e57e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":728,
              "y":132},
            "size":{
              "width":107,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"db1fbf8d449545fa9ec6b35b2db62996",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":214},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8d2f0e79793e43a789dc867841214885",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":415},
            "size":{
              "width":179,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"919d52fb277a4193b7b7d4ee075ca9a4",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":301},
            "size":{
              "width":189,
              "height":61}},
          "adaptiveStyles":{
}},
{
          "id":"bb71e122ceb4484787144634e6a1cbfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":780,
              "y":32},
            "size":{
              "width":130,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01e16ad42a54209bff758440c6c9c87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":32},
                "size":{
                  "width":130,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u98.png"}},
{
          "id":"910b2b33605549fda7fe3f769cf4836d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":129},
            "size":{
              "width":200,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18b1d8d47634f09ac8919953c138641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":129},
                "size":{
                  "width":200,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ed1b6544020481ab00b5158216c3764",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":555},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6b3291398a4ba7b4449807d493d21c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":555},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"31807912e7cb48b6805d504681fbae7d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":581},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2798fff60d441bfa09f060f464a0978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":581},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"722eed63e15c42d9b2975af8898b1685",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":607},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71334cca2eaa418d9655e35cc3253517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":607},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9b6bba53e62042edba5cf1e201ae5c39",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":633},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3795e96fc9e94d5391b94b3ba28fb2f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":633},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b8a93c2f164d42009b08f4b5b930e0eb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":659},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef441f9212d24b8cb8b33737825d6843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":659},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"49176ce24e9742beb54b86cd6f4754df",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":683},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b72dcccdc44cacbb8e97e6f04ab24d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":683},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c2596a8acf7c437f88b4325684b6cc49",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":735},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b22e96ecb54c7692c66af717db8300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":735},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cc0557f165ec481199df933a61a8b682",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":761},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f698777d98904258ac03a35cf6b8915c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":761},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c121015541ff4550b4cc8300bed6a6ca",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":787},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed00833f1ca641c1871f85aca163c9f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":787},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"be3d9015f6e545d6b8ba619a1fe8648a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":813},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1558510596964a2da8816631ee8aa9f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":813},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3a5ea9b241e94a6e84c4eb68f407f61a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":839},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ecd3bd9e105419181da72ca3fb88be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":839},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b0027f7fc6c04c9296546d4cc8784ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":347,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367ff54c038d48e7aa66929abd0e81cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":347,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e29e0e044e6a48ccb2c5fe1ad74348bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":501},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64804e90c5ea471fb2b2a0e1d40e9583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":501},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1ba5572fe09441cbe7f28269b99b8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":527},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24816f88778f4a8dbd059969a09c176a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":527},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bcdfd0834544c95a2f49ea0dfe33de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":41,
              "y":709},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"550e3084c678429bad5da3a0f7395a46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":709},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcc1f3770c7d4c57b2444ed6af5e2110",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28471c246f974b1b93cee4b3f99f816f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0793a100fcf45e49cde0daad64dc340",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"077bd4c0da2c48558b42ead46a32d741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1fd9f0647ac461fba4a02f4edbd5f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":192},
            "size":{
              "width":289,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c17de1ee324c0ca5fe7b4bcb30f128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":192},
                "size":{
                  "width":289,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51bd5551577f4df4b946429113452add",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":350,
              "y":128},
            "size":{
              "width":93,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f1ff96adf34c318b2689a79302829f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":128},
                "size":{
                  "width":93,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u40.png"}},
{
          "id":"2b5b4dbdc4264d45b28a1f537a0210e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":453,
              "y":128},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c66d030d984ae889bdaba949f20900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":128},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u42.png"}},
{
          "id":"00962436e6604e85a4af2a0a3f54f0fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":658,
              "y":135},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62bb985385874ba6abbb67a765673862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":658,
                  "y":135},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fba33e9347484f3e80cbf9bf4da2e638",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":533,
              "y":128},
            "size":{
              "width":115,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"185efa7872e04f85b968d863dba4fa6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":128},
                "size":{
                  "width":115,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u86.png"}},
{
          "id":"4eff8f6cf7244f98bd2d42cf1ed33b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":350,
              "y":80},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a77bb50c84e40b993c7d0876e0b04a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":80},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"0d058675f031426dab4a070c34f329d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":636,
              "y":80},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287657bdf76442fa8abb9f13d79dfe45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":80},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Добавление из альбома in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"добавление_из_альбома.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"0ac91fd477b54a1b8eb208f8c204d484",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":780,
              "y":80},
            "size":{
              "width":130,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6339f32f1e1943ae881bab0a3304ef78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":80},
                "size":{
                  "width":130,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show Загрузка",
                      "objectsToFades":[{
                          "objectPath":["e1d7cdffc14143dfb632e42f30cb37e0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u98.png"}},
{
          "id":"bfd486ee5bce49108b73d34b53cf022c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":636,
              "y":32},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940567464f0d447cb5a7bf8491bae835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":32},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/редактирование/u100.png"}},
{
          "id":"645ab08c1eed4a9591cf1b707319331d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":494,
              "y":80},
            "size":{
              "width":132,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fdc6e6cb4cd479384971ffc284c5495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":80},
                "size":{
                  "width":132,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/редактирование/u106.png"}},
{
          "id":"e1d7cdffc14143dfb632e42f30cb37e0",
          "label":"Загрузка",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":97,
              "y":10},
            "size":{
              "width":683,
              "height":560},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02797d84e8204f49af05c7c60735304d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":97,
                  "y":10},
                "size":{
                  "width":683,
                  "height":560},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Редактирование in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"редактирование.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/админка/загрузка_u12.PNG"}}]}},
  "masters":{
},
  "objectPaths":{
    "99ae70a4568b403a846fca3ceb6d5f0c":{
      "scriptId":"u0"},
    "756e1a673f2a4d8db543b8b37c83a0af":{
      "scriptId":"u1"},
    "f598cb6016104b09b81f54f90bed7819":{
      "scriptId":"u2"},
    "6c257a5028dd4091ab79f150bb6c758a":{
      "scriptId":"u3"},
    "abe7ae873d2942649bde073946090b2a":{
      "scriptId":"u4"},
    "90e000c4138f4005aa7c67f51a24f317":{
      "scriptId":"u5"},
    "aca10be763dd4233af3915853e18617c":{
      "scriptId":"u6"},
    "47615c16ac464a52bf58c3f336964527":{
      "scriptId":"u7"},
    "4af693a1de0c4ccd99eda21e4580e57e":{
      "scriptId":"u8"},
    "db1fbf8d449545fa9ec6b35b2db62996":{
      "scriptId":"u9"},
    "8d2f0e79793e43a789dc867841214885":{
      "scriptId":"u10"},
    "919d52fb277a4193b7b7d4ee075ca9a4":{
      "scriptId":"u11"},
    "bb71e122ceb4484787144634e6a1cbfe":{
      "scriptId":"u12"},
    "c01e16ad42a54209bff758440c6c9c87":{
      "scriptId":"u13"},
    "910b2b33605549fda7fe3f769cf4836d":{
      "scriptId":"u14"},
    "f18b1d8d47634f09ac8919953c138641":{
      "scriptId":"u15"},
    "5ed1b6544020481ab00b5158216c3764":{
      "scriptId":"u16"},
    "ab6b3291398a4ba7b4449807d493d21c":{
      "scriptId":"u17"},
    "31807912e7cb48b6805d504681fbae7d":{
      "scriptId":"u18"},
    "e2798fff60d441bfa09f060f464a0978":{
      "scriptId":"u19"},
    "722eed63e15c42d9b2975af8898b1685":{
      "scriptId":"u20"},
    "71334cca2eaa418d9655e35cc3253517":{
      "scriptId":"u21"},
    "9b6bba53e62042edba5cf1e201ae5c39":{
      "scriptId":"u22"},
    "3795e96fc9e94d5391b94b3ba28fb2f2":{
      "scriptId":"u23"},
    "b8a93c2f164d42009b08f4b5b930e0eb":{
      "scriptId":"u24"},
    "ef441f9212d24b8cb8b33737825d6843":{
      "scriptId":"u25"},
    "49176ce24e9742beb54b86cd6f4754df":{
      "scriptId":"u26"},
    "e1b72dcccdc44cacbb8e97e6f04ab24d":{
      "scriptId":"u27"},
    "c2596a8acf7c437f88b4325684b6cc49":{
      "scriptId":"u28"},
    "38b22e96ecb54c7692c66af717db8300":{
      "scriptId":"u29"},
    "cc0557f165ec481199df933a61a8b682":{
      "scriptId":"u30"},
    "f698777d98904258ac03a35cf6b8915c":{
      "scriptId":"u31"},
    "c121015541ff4550b4cc8300bed6a6ca":{
      "scriptId":"u32"},
    "ed00833f1ca641c1871f85aca163c9f3":{
      "scriptId":"u33"},
    "be3d9015f6e545d6b8ba619a1fe8648a":{
      "scriptId":"u34"},
    "1558510596964a2da8816631ee8aa9f2":{
      "scriptId":"u35"},
    "3a5ea9b241e94a6e84c4eb68f407f61a":{
      "scriptId":"u36"},
    "0ecd3bd9e105419181da72ca3fb88be4":{
      "scriptId":"u37"},
    "b0027f7fc6c04c9296546d4cc8784ee4":{
      "scriptId":"u38"},
    "367ff54c038d48e7aa66929abd0e81cd":{
      "scriptId":"u39"},
    "e29e0e044e6a48ccb2c5fe1ad74348bd":{
      "scriptId":"u40"},
    "64804e90c5ea471fb2b2a0e1d40e9583":{
      "scriptId":"u41"},
    "d1ba5572fe09441cbe7f28269b99b8ad":{
      "scriptId":"u42"},
    "24816f88778f4a8dbd059969a09c176a":{
      "scriptId":"u43"},
    "5bcdfd0834544c95a2f49ea0dfe33de7":{
      "scriptId":"u44"},
    "550e3084c678429bad5da3a0f7395a46":{
      "scriptId":"u45"},
    "bcc1f3770c7d4c57b2444ed6af5e2110":{
      "scriptId":"u46"},
    "28471c246f974b1b93cee4b3f99f816f":{
      "scriptId":"u47"},
    "b0793a100fcf45e49cde0daad64dc340":{
      "scriptId":"u48"},
    "077bd4c0da2c48558b42ead46a32d741":{
      "scriptId":"u49"},
    "d1fd9f0647ac461fba4a02f4edbd5f0e":{
      "scriptId":"u50"},
    "b1c17de1ee324c0ca5fe7b4bcb30f128":{
      "scriptId":"u51"},
    "51bd5551577f4df4b946429113452add":{
      "scriptId":"u52"},
    "10f1ff96adf34c318b2689a79302829f":{
      "scriptId":"u53"},
    "2b5b4dbdc4264d45b28a1f537a0210e0":{
      "scriptId":"u54"},
    "96c66d030d984ae889bdaba949f20900":{
      "scriptId":"u55"},
    "00962436e6604e85a4af2a0a3f54f0fb":{
      "scriptId":"u56"},
    "62bb985385874ba6abbb67a765673862":{
      "scriptId":"u57"},
    "fba33e9347484f3e80cbf9bf4da2e638":{
      "scriptId":"u58"},
    "185efa7872e04f85b968d863dba4fa6d":{
      "scriptId":"u59"},
    "4eff8f6cf7244f98bd2d42cf1ed33b2a":{
      "scriptId":"u60"},
    "1a77bb50c84e40b993c7d0876e0b04a0":{
      "scriptId":"u61"},
    "0d058675f031426dab4a070c34f329d6":{
      "scriptId":"u62"},
    "287657bdf76442fa8abb9f13d79dfe45":{
      "scriptId":"u63"},
    "0ac91fd477b54a1b8eb208f8c204d484":{
      "scriptId":"u64"},
    "6339f32f1e1943ae881bab0a3304ef78":{
      "scriptId":"u65"},
    "bfd486ee5bce49108b73d34b53cf022c":{
      "scriptId":"u66"},
    "940567464f0d447cb5a7bf8491bae835":{
      "scriptId":"u67"},
    "645ab08c1eed4a9591cf1b707319331d":{
      "scriptId":"u68"},
    "0fdc6e6cb4cd479384971ffc284c5495":{
      "scriptId":"u69"},
    "e1d7cdffc14143dfb632e42f30cb37e0":{
      "scriptId":"u70"},
    "02797d84e8204f49af05c7c60735304d":{
      "scriptId":"u71"}}});