$axure.loadCurrentPage({
  "url":"управление_папками.html",
  "generationDate":new Date(1429122561725.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"93486efe94244fd09f57bdbcb8b9322d",
    "type":"Axure:Page",
    "name":"Управление папками",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0614bef9503f43ff87493323ec394b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":551,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"202b68fcc7034e80bb048e0c525d112d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":551,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e785287c2a964aa5987bab93f9f3419b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4b7a55b6a1d445189dd5734fc51cd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbb2f5fee1904592bf40b5d69de9fc9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":67},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e8a7803560436fa3a89a34cabea8bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":67},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a598e6a1cf014c9b8385e7dbd1a36467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbe7620f811048259e114ac5e53a9b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u6.png"}},
{
          "id":"08c1cb178ff647368c5ae277badb6285",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":130},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828afa967cf345349035bd77537ffc9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":130},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u6.png"}},
{
          "id":"2040c4ccbead4f6ebf9ca275752316e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":290},
            "size":{
              "width":76,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62028b9f1bd141e1a894b19959cc7a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":290},
                "size":{
                  "width":76,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u10.png"}},
{
          "id":"7cf0b2b719824dc9a68359c40996a321",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":370},
            "size":{
              "width":76,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118f222c76a54012bbd37fffd9196eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":370},
                "size":{
                  "width":76,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u10.png"}},
{
          "id":"e412ea22357e4dbd93298799b0431a9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":76,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63b205981a2749a3b3e68849e1d632c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":330},
                "size":{
                  "width":76,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u10.png"}},
{
          "id":"88b4418dbb2f4593a32c6c346a294f2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":330},
            "size":{
              "width":76,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b99c52a44a24b0bab4621da28b168d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":330},
                "size":{
                  "width":76,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u10.png"}},
{
          "id":"81767abb287744ccb23aac4690ba4484",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":250},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42e2358ebb5451e902d2129e540b519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":250},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u6.png"}},
{
          "id":"d53d5bbc3ec442a682116230f98f4093",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":231,
              "y":130},
            "size":{
              "width":219,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac67ccbfde6a4b73bc4c23d5ee84078f",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9100300d559444e96f4e07fdce88149",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Italic', 'Arial'",
                    "fontStyle":"italic",
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "size":{
                      "width":85,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6911ad039544d1aa33e98bd85f4cfaf",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Italic', 'Arial'",
                        "fontStyle":"italic",
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "size":{
                          "width":85,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}},
{
                  "id":"4314d553366540acaa07a102278627de",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Italic', 'Arial'",
                    "fontStyle":"italic",
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":122,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3faac7e250b74c359ad24f6e213a32df",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Italic', 'Arial'",
                        "fontStyle":"italic",
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":122,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7b2e08720f3846529c2f92d95aefddc4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Italic', 'Arial'",
                            "fontStyle":"italic",
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":122,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}},
{
                      "id":"cfe6036865f749dd94f102af02047fec",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":119,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"640c358a093042fc9d814eec039958f6",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":119,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"4c13b144fbb940d9857605856414123e",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":119,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"640c358a093042fc9d814eec039958f6"},
{
                      "id":"bf5318d468b14fe89d431cc59831cbde",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2d31cece431c4103bf661f1a26fa5ef6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/добавление_из_альбома/u51.png",
                        "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                      "id":"77a6f512afa844d0ac488b63ec8d218e",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":121,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e996d5450cec4b8fa7def8920ca31f5a",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":121,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0ddadbe833a4471784668158020aad8f",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":80},
                                "size":{
                                  "width":121,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"e996d5450cec4b8fa7def8920ca31f5a"},
{
                      "id":"837e46fb734c45cfa6a34ba38fd272a2",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":126,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0346fd1059a34b938d159a27e5d2fdcb",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":126,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"21a01da2e7074e5395bc0b25f34aeed8",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":60},
                                "size":{
                                  "width":126,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"0346fd1059a34b938d159a27e5d2fdcb"},
{
                      "id":"a3e8c5412815462295e36c96234b7492",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":172,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"aae3a8d3997142a68d853263ac339c13",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":172,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e72d123d26c04581a47a1bdc30fabd0b",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
                                    "fontWeight":"bold"}},
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":172,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "selected~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"aae3a8d3997142a68d853263ac339c13"}],
                  "buttonShapeId":"3faac7e250b74c359ad24f6e213a32df"},
{
                  "id":"88431c1ca90145bd928e9ad2930edb26",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5c56ad3389b4ce6b9048cbf488a1447",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/добавление_из_альбома/u51.png",
                    "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                  "id":"08a4f18222eb497d86362179bcc66ffc",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":120},
                    "size":{
                      "width":129,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca7c9873231744d29b772f35c4864a71",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":120},
                        "size":{
                          "width":129,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"48016aa737444cb69a7115fe97e5ca4e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":120},
                            "size":{
                              "width":129,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"ca7c9873231744d29b772f35c4864a71"},
{
                  "id":"a87ded380a824eac883d82b701b84b3b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":140},
                    "size":{
                      "width":199,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca7c861f5a52443ea6facefd2851b15f",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":140},
                        "size":{
                          "width":199,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"362ec39f2df540eabeb0ddfeeac74544",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":140},
                            "size":{
                              "width":199,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"ca7c861f5a52443ea6facefd2851b15f"}],
              "buttonShapeId":"d9100300d559444e96f4e07fdce88149"},
{
              "id":"4ab5be27d94643f0a62403455fd1e131",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":128,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d56758c74eba46948afe79958d472b11",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":0,
                      "y":260},
                    "size":{
                      "width":128,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b5d77f3fb194f23a416d9b86df0dc40",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":0,
                          "y":260},
                        "size":{
                          "width":128,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}}],
              "buttonShapeId":"d56758c74eba46948afe79958d472b11"},
{
              "id":"13f4e8b8e5194ebf9f1d7a5603b4a4db",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":140,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e5d9ea9e9d042af8a2e2e094d4eba1a",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Italic', 'Arial'",
                    "fontStyle":"italic",
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":140,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d82d0a7e224b479fbcf2118f9bd2b759",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Italic', 'Arial'",
                        "fontStyle":"italic",
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":140,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif"}},
{
                  "id":"1e69e7ef71a6431cab70ef98dbd3247c",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":142,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cac98dc4c524bdca462ae7f88371cbd",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":142,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ef1ed21a8a354f159dc3d3a389971c43",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":142,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"7cac98dc4c524bdca462ae7f88371cbd"},
{
                  "id":"de208dc595c940f0bf75ba3c7c79c1fe",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9da0fa4606804a58a14c16fc3054b84c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/добавление_из_альбома/u51.png",
                    "selected~":"images/добавление_из_альбома/u51_selected.png"}},
{
                  "id":"f7de7fe1db8d46c8aa4f0a3300ef96c8",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":129,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c5b309cf4124966ab26cd95b2bfc70d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":129,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"eefb79ab55e646f5ad81544e895e0be2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":129,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"1c5b309cf4124966ab26cd95b2bfc70d"},
{
                  "id":"6353fc322da14edd8a7c5405b1da052f",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"972f8611c4f84309983799d13363c520",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":66,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"235a9848a50941c6a5f30da2d784254c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":66,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"972f8611c4f84309983799d13363c520"},
{
                  "id":"f61e69fb8d5d4fb7bcf2223029e60cc9",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
                        "fontWeight":"bold"}},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":105,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3077817865ad45f39ddae71e68cd39f6",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
                            "fontWeight":"bold"}},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":105,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5b35afd2288a446b83c331b1fe74b444",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
                                "fontWeight":"bold"}},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":105,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif",
                        "selected~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"3077817865ad45f39ddae71e68cd39f6"}],
              "buttonShapeId":"9e5d9ea9e9d042af8a2e2e094d4eba1a"}]},
{
          "id":"6ae6458aaf1340b8a185eb75d832ea20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":20,
              "y":410},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436ad88863fb4d03bf84db5e65409b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":20,
                  "y":410},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Админка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"админка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/управление_папками/u6.png"}},
{
          "id":"de41d3cb4d804c10acdb325fbc97627d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":20,
              "y":450},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc9fec6267a4a978d46f4897147895a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":20,
                  "y":450},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Результат управления папками in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"результат_управления_папками.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/управление_папками/u6.png"}},
{
          "id":"1568e03ad2e24ba7aae0b6c8f07eac9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":164,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d6bda4022b4411887227133245c13b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":210},
                "size":{
                  "width":164,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/управление_папками/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0614bef9503f43ff87493323ec394b3b":{
      "scriptId":"u0"},
    "202b68fcc7034e80bb048e0c525d112d":{
      "scriptId":"u1"},
    "e785287c2a964aa5987bab93f9f3419b":{
      "scriptId":"u2"},
    "b4b7a55b6a1d445189dd5734fc51cd70":{
      "scriptId":"u3"},
    "fbb2f5fee1904592bf40b5d69de9fc9e":{
      "scriptId":"u4"},
    "16e8a7803560436fa3a89a34cabea8bd":{
      "scriptId":"u5"},
    "a598e6a1cf014c9b8385e7dbd1a36467":{
      "scriptId":"u6"},
    "cbe7620f811048259e114ac5e53a9b46":{
      "scriptId":"u7"},
    "08c1cb178ff647368c5ae277badb6285":{
      "scriptId":"u8"},
    "828afa967cf345349035bd77537ffc9e":{
      "scriptId":"u9"},
    "2040c4ccbead4f6ebf9ca275752316e8":{
      "scriptId":"u10"},
    "62028b9f1bd141e1a894b19959cc7a47":{
      "scriptId":"u11"},
    "7cf0b2b719824dc9a68359c40996a321":{
      "scriptId":"u12"},
    "118f222c76a54012bbd37fffd9196eff":{
      "scriptId":"u13"},
    "e412ea22357e4dbd93298799b0431a9c":{
      "scriptId":"u14"},
    "63b205981a2749a3b3e68849e1d632c9":{
      "scriptId":"u15"},
    "88b4418dbb2f4593a32c6c346a294f2d":{
      "scriptId":"u16"},
    "2b99c52a44a24b0bab4621da28b168d9":{
      "scriptId":"u17"},
    "81767abb287744ccb23aac4690ba4484":{
      "scriptId":"u18"},
    "a42e2358ebb5451e902d2129e540b519":{
      "scriptId":"u19"},
    "d53d5bbc3ec442a682116230f98f4093":{
      "scriptId":"u20"},
    "ac67ccbfde6a4b73bc4c23d5ee84078f":{
      "scriptId":"u21"},
    "88431c1ca90145bd928e9ad2930edb26":{
      "scriptId":"u22"},
    "c5c56ad3389b4ce6b9048cbf488a1447":{
      "scriptId":"u23"},
    "d9100300d559444e96f4e07fdce88149":{
      "scriptId":"u24"},
    "f6911ad039544d1aa33e98bd85f4cfaf":{
      "scriptId":"u25"},
    "4314d553366540acaa07a102278627de":{
      "scriptId":"u26"},
    "bf5318d468b14fe89d431cc59831cbde":{
      "scriptId":"u27"},
    "2d31cece431c4103bf661f1a26fa5ef6":{
      "scriptId":"u28"},
    "3faac7e250b74c359ad24f6e213a32df":{
      "scriptId":"u29"},
    "7b2e08720f3846529c2f92d95aefddc4":{
      "scriptId":"u30"},
    "cfe6036865f749dd94f102af02047fec":{
      "scriptId":"u31"},
    "640c358a093042fc9d814eec039958f6":{
      "scriptId":"u32"},
    "4c13b144fbb940d9857605856414123e":{
      "scriptId":"u33"},
    "a3e8c5412815462295e36c96234b7492":{
      "scriptId":"u34"},
    "aae3a8d3997142a68d853263ac339c13":{
      "scriptId":"u35"},
    "e72d123d26c04581a47a1bdc30fabd0b":{
      "scriptId":"u36"},
    "837e46fb734c45cfa6a34ba38fd272a2":{
      "scriptId":"u37"},
    "0346fd1059a34b938d159a27e5d2fdcb":{
      "scriptId":"u38"},
    "21a01da2e7074e5395bc0b25f34aeed8":{
      "scriptId":"u39"},
    "77a6f512afa844d0ac488b63ec8d218e":{
      "scriptId":"u40"},
    "e996d5450cec4b8fa7def8920ca31f5a":{
      "scriptId":"u41"},
    "0ddadbe833a4471784668158020aad8f":{
      "scriptId":"u42"},
    "08a4f18222eb497d86362179bcc66ffc":{
      "scriptId":"u43"},
    "ca7c9873231744d29b772f35c4864a71":{
      "scriptId":"u44"},
    "48016aa737444cb69a7115fe97e5ca4e":{
      "scriptId":"u45"},
    "a87ded380a824eac883d82b701b84b3b":{
      "scriptId":"u46"},
    "ca7c861f5a52443ea6facefd2851b15f":{
      "scriptId":"u47"},
    "362ec39f2df540eabeb0ddfeeac74544":{
      "scriptId":"u48"},
    "13f4e8b8e5194ebf9f1d7a5603b4a4db":{
      "scriptId":"u49"},
    "de208dc595c940f0bf75ba3c7c79c1fe":{
      "scriptId":"u50"},
    "9da0fa4606804a58a14c16fc3054b84c":{
      "scriptId":"u51"},
    "9e5d9ea9e9d042af8a2e2e094d4eba1a":{
      "scriptId":"u52"},
    "d82d0a7e224b479fbcf2118f9bd2b759":{
      "scriptId":"u53"},
    "1e69e7ef71a6431cab70ef98dbd3247c":{
      "scriptId":"u54"},
    "7cac98dc4c524bdca462ae7f88371cbd":{
      "scriptId":"u55"},
    "ef1ed21a8a354f159dc3d3a389971c43":{
      "scriptId":"u56"},
    "f7de7fe1db8d46c8aa4f0a3300ef96c8":{
      "scriptId":"u57"},
    "1c5b309cf4124966ab26cd95b2bfc70d":{
      "scriptId":"u58"},
    "eefb79ab55e646f5ad81544e895e0be2":{
      "scriptId":"u59"},
    "6353fc322da14edd8a7c5405b1da052f":{
      "scriptId":"u60"},
    "972f8611c4f84309983799d13363c520":{
      "scriptId":"u61"},
    "235a9848a50941c6a5f30da2d784254c":{
      "scriptId":"u62"},
    "f61e69fb8d5d4fb7bcf2223029e60cc9":{
      "scriptId":"u63"},
    "3077817865ad45f39ddae71e68cd39f6":{
      "scriptId":"u64"},
    "5b35afd2288a446b83c331b1fe74b444":{
      "scriptId":"u65"},
    "4ab5be27d94643f0a62403455fd1e131":{
      "scriptId":"u66"},
    "d56758c74eba46948afe79958d472b11":{
      "scriptId":"u67"},
    "8b5d77f3fb194f23a416d9b86df0dc40":{
      "scriptId":"u68"},
    "6ae6458aaf1340b8a185eb75d832ea20":{
      "scriptId":"u69"},
    "436ad88863fb4d03bf84db5e65409b62":{
      "scriptId":"u70"},
    "de41d3cb4d804c10acdb325fbc97627d":{
      "scriptId":"u71"},
    "1bc9fec6267a4a978d46f4897147895a":{
      "scriptId":"u72"},
    "1568e03ad2e24ba7aae0b6c8f07eac9c":{
      "scriptId":"u73"},
    "b4d6bda4022b4411887227133245c13b":{
      "scriptId":"u74"}}});