$axure.loadCurrentPage({
  "url":"фотка.html",
  "generationDate":new Date(1429122555017.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0fe56d8f1b1540ce837b831298ea3ce3",
    "type":"Axure:Page",
    "name":"Фотка",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cf09f75cd75f4cc09af7d8ff6ec32593",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":110},
            "size":{
              "width":710,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b4d89008dd84af78e9ccd12ff278d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":110},
                "size":{
                  "width":710,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/фотка/u0.png"}},
{
          "id":"cd1d21d73eac44f1a5499dee734a80c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":292,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7c54c92da824cff98bda3c365cebec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":292,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b17ac6594b3b4e1a97b27d6c363de1a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":66},
            "size":{
              "width":135,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330581b80337430c8f6097ef02d461af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":66},
                "size":{
                  "width":135,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фото по поездкам in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фото_по_поездкам.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b8b245259074e2cbd6c8d91853343ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":140,
              "y":470},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7006d845f1c445e8c0d8da2a6dd59ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":140,
                  "y":470},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/фотка/u6.png"}},
{
          "id":"e517145a742642958f88b44c383847e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":66},
            "size":{
              "width":167,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3d1441e8e2443a1987d16b8be5c3f4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":66},
                "size":{
                  "width":167,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Псков 2014 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"псков_2014.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a77cf48eda2a4749b4e566341139d51c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":66},
            "size":{
              "width":303,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ab4f2cff1d4653a70ff6ff2060841b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":525,
                  "y":66},
                "size":{
                  "width":303,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open День 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"день_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3820d6881c844bdba649f49f4a97519",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":510,
              "y":470},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6555eab58373414d9ed5da79ff722966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":510,
                  "y":470},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Фотка in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"фотка.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/фотка/u6.png"}},
{
          "id":"039d2ac020d440fda6a5cd3c30e93da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":524},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1e628b9876343f59dee8f3aef3f297f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":524},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfddd2efdd734932bdcd0a2a826d7aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":550},
            "size":{
              "width":710,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e837d167d36485ca5c0a23f266f3c7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":550},
                "size":{
                  "width":710,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9767acdcdd23435db210dbe03add3584",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":640},
            "size":{
              "width":135,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0262d7cef94417b82c7d9aee99e1ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":640},
                "size":{
                  "width":135,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle EXIF",
                      "objectsToFades":[{
                          "objectPath":["6eb172cf4aa84b3ebd7c6d20fff09bde"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/фотка/u18.png"}},
{
          "id":"6eb172cf4aa84b3ebd7c6d20fff09bde",
          "label":"EXIF",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":680},
            "size":{
              "width":630,
              "height":512},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34bc64876afb46ccaa98066530a8903c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":20,
                  "y":680},
                "size":{
                  "width":630,
                  "height":512},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1452e48d2d4748bf87b9c89f859b8923",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":470},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c44495e3319a43a0a564e1cfe4242043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":470},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/фотка/u6.png"}},
{
          "id":"402e5f48087243c6b792de8391b10709",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":67},
            "size":{
              "width":174,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71a6deea1c5d45fe8659dbedeeeffc23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":67},
                "size":{
                  "width":174,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4abf219666849c288be618ae5c58601",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":600},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6cc52c6f8e4d4a9599b1f401ad561e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":603},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21566eabfe6e4b8e8269d52c2371ebf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":603},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ec7e7d46a9e4b3c8942283e98a7e788",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":596},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77aa4e465ce44604b24e2e4dc94e2dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":596},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/фотка/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cf09f75cd75f4cc09af7d8ff6ec32593":{
      "scriptId":"u0"},
    "3b4d89008dd84af78e9ccd12ff278d90":{
      "scriptId":"u1"},
    "cd1d21d73eac44f1a5499dee734a80c0":{
      "scriptId":"u2"},
    "f7c54c92da824cff98bda3c365cebec4":{
      "scriptId":"u3"},
    "b17ac6594b3b4e1a97b27d6c363de1a7":{
      "scriptId":"u4"},
    "330581b80337430c8f6097ef02d461af":{
      "scriptId":"u5"},
    "4b8b245259074e2cbd6c8d91853343ef":{
      "scriptId":"u6"},
    "e7006d845f1c445e8c0d8da2a6dd59ca":{
      "scriptId":"u7"},
    "e517145a742642958f88b44c383847e0":{
      "scriptId":"u8"},
    "b3d1441e8e2443a1987d16b8be5c3f4b":{
      "scriptId":"u9"},
    "a77cf48eda2a4749b4e566341139d51c":{
      "scriptId":"u10"},
    "67ab4f2cff1d4653a70ff6ff2060841b":{
      "scriptId":"u11"},
    "f3820d6881c844bdba649f49f4a97519":{
      "scriptId":"u12"},
    "6555eab58373414d9ed5da79ff722966":{
      "scriptId":"u13"},
    "039d2ac020d440fda6a5cd3c30e93da9":{
      "scriptId":"u14"},
    "b1e628b9876343f59dee8f3aef3f297f":{
      "scriptId":"u15"},
    "bfddd2efdd734932bdcd0a2a826d7aff":{
      "scriptId":"u16"},
    "6e837d167d36485ca5c0a23f266f3c7b":{
      "scriptId":"u17"},
    "9767acdcdd23435db210dbe03add3584":{
      "scriptId":"u18"},
    "6f0262d7cef94417b82c7d9aee99e1ca":{
      "scriptId":"u19"},
    "6eb172cf4aa84b3ebd7c6d20fff09bde":{
      "scriptId":"u20"},
    "34bc64876afb46ccaa98066530a8903c":{
      "scriptId":"u21"},
    "1452e48d2d4748bf87b9c89f859b8923":{
      "scriptId":"u22"},
    "c44495e3319a43a0a564e1cfe4242043":{
      "scriptId":"u23"},
    "402e5f48087243c6b792de8391b10709":{
      "scriptId":"u24"},
    "71a6deea1c5d45fe8659dbedeeeffc23":{
      "scriptId":"u25"},
    "a4abf219666849c288be618ae5c58601":{
      "scriptId":"u26"},
    "6cc52c6f8e4d4a9599b1f401ad561e21":{
      "scriptId":"u27"},
    "21566eabfe6e4b8e8269d52c2371ebf2":{
      "scriptId":"u28"},
    "8ec7e7d46a9e4b3c8942283e98a7e788":{
      "scriptId":"u29"},
    "77aa4e465ce44604b24e2e4dc94e2dc0":{
      "scriptId":"u30"}}});